// Clinical data for the session "Diagnose" and "Prescribe" pickers.
// Diagnosis options are per-scenario (keyed by scenario slug); one option per
// list is the correct one — but it is NOT marked here, grading happens on the
// backend. The medication formulary is shared across all scenarios.

export interface Bi { ru: string; kk: string; en: string }

/* ── Diagnosis options ──────────────────────────────────────── */

export const DIAGNOSIS_OPTIONS: Record<string, Bi[]> = {
  arvi_adult: [
    { ru: "J06.9 — ОРВИ (острая инфекция верхних дыхательных путей)", kk: "J06.9 — ЖРВИ (жоғарғы тыныс жолдарының жедел инфекциясы)", en: "J06.9 — URI (acute upper respiratory tract infection)" },
    { ru: "J02.9 — Острый фарингит", kk: "J02.9 — Жедел фарингит", en: "J02.9 — Acute pharyngitis" },
    { ru: "J03.9 — Острый тонзиллит (ангина)", kk: "J03.9 — Жедел тонзиллит (ангина)", en: "J03.9 — Acute tonsillitis" },
    { ru: "J11 — Грипп", kk: "J11 — Тұмау", en: "J11 — Influenza" },
    { ru: "J01.9 — Острый синусит", kk: "J01.9 — Жедел синусит", en: "J01.9 — Acute sinusitis" },
  ],
  pneumonia_community: [
    { ru: "J18.1 — Внебольничная долевая пневмония (правосторонняя)", kk: "J18.1 — Аурухана сыртылық бөлімді пневмония (оң жақты)", en: "J18.1 — Community-acquired lobar pneumonia (right-sided)" },
    { ru: "J20.9 — Острый бронхит", kk: "J20.9 — Жедел бронхит", en: "J20.9 — Acute bronchitis" },
    { ru: "J44.1 — ХОБЛ, обострение", kk: "J44.1 — СОЗТ, өршу", en: "J44.1 — COPD, exacerbation" },
    { ru: "A15.0 — Туберкулёз лёгких", kk: "A15.0 — Өкпе туберкулёзі", en: "A15.0 — Pulmonary tuberculosis" },
    { ru: "J06.9 — ОРВИ", kk: "J06.9 — ЖРВИ", en: "J06.9 — URI" },
  ],
  brucellosis: [
    { ru: "A23.9 — Бруцеллёз (острая форма)", kk: "A23.9 — Бруцеллёз (жіті форма)", en: "A23.9 — Brucellosis (acute form)" },
    { ru: "A01.0 — Брюшной тиф", kk: "A01.0 — Іш сүзегі", en: "A01.0 — Typhoid fever" },
    { ru: "A15.0 — Туберкулёз", kk: "A15.0 — Туберкулёз", en: "A15.0 — Tuberculosis" },
    { ru: "M06.9 — Ревматоидный артрит", kk: "M06.9 — Ревматоидты артрит", en: "M06.9 — Rheumatoid arthritis" },
    { ru: "C81 — Лимфома Ходжкина", kk: "C81 — Ходжкин лимфомасы", en: "C81 — Hodgkin lymphoma" },
  ],
  iron_deficiency_anemia: [
    { ru: "D50.9 — Железодефицитная анемия", kk: "D50.9 — Темір тапшылығы анемиясы", en: "D50.9 — Iron-deficiency anemia" },
    { ru: "D51.0 — B12-дефицитная анемия", kk: "D51.0 — B12-тапшылық анемиясы", en: "D51.0 — Vitamin B12-deficiency anemia" },
    { ru: "E03.9 — Гипотиреоз", kk: "E03.9 — Гипотиреоз", en: "E03.9 — Hypothyroidism" },
    { ru: "I50.9 — Хроническая сердечная недостаточность", kk: "I50.9 — Созылмалы жүрек жеткіліксіздігі", en: "I50.9 — Chronic heart failure" },
    { ru: "F48.0 — Синдром хронической усталости", kk: "F48.0 — Созылмалы шаршау синдромы", en: "F48.0 — Chronic fatigue syndrome" },
  ],
  community_pneumonia: [
    { ru: "J18.9 — Внебольничная пневмония средней тяжести", kk: "J18.9 — Орташа ауырлықтағы аурухана сыртылық пневмония", en: "J18.9 — Community-acquired pneumonia, moderate severity" },
    { ru: "J20.9 — Острый бронхит", kk: "J20.9 — Жедел бронхит", en: "J20.9 — Acute bronchitis" },
    { ru: "J44.1 — ХОБЛ, обострение", kk: "J44.1 — СОЗТ, өршу", en: "J44.1 — COPD, exacerbation" },
    { ru: "J06.9 — ОРВИ", kk: "J06.9 — ЖРВИ", en: "J06.9 — URI" },
    { ru: "A15.0 — Туберкулёз лёгких", kk: "A15.0 — Өкпе туберкулёзі", en: "A15.0 — Pulmonary tuberculosis" },
  ],
  hypertension_crisis: [
    { ru: "I10 — Гипертонический криз без поражения органов-мишеней", kk: "I10 — Нысана мүшелері зақымдалмаған гипертониялық дағдарыс", en: "I10 — Hypertensive crisis without target organ damage" },
    { ru: "I60 — Субарахноидальное кровоизлияние", kk: "I60 — Субарахноидалды қан құйылу", en: "I60 — Subarachnoid hemorrhage" },
    { ru: "G43.0 — Мигрень", kk: "G43.0 — Мигрень", en: "G43.0 — Migraine" },
    { ru: "I63 — Ишемический инсульт", kk: "I63 — Ишемиялық инсульт", en: "I63 — Ischemic stroke" },
    { ru: "H81.1 — Доброкачественное позиционное головокружение", kk: "H81.1 — Қатерсіз позициялық бас айналу", en: "H81.1 — Benign paroxysmal positional vertigo" },
  ],
  diabetes_t2_debut: [
    { ru: "E11.9 — Сахарный диабет 2 типа, впервые выявленный", kk: "E11.9 — 2 тип қант диабеті, алғаш анықталған", en: "E11.9 — Type 2 diabetes mellitus, newly diagnosed" },
    { ru: "E10.9 — Сахарный диабет 1 типа", kk: "E10.9 — 1 тип қант диабеті", en: "E10.9 — Type 1 diabetes mellitus" },
    { ru: "E23.2 — Несахарный диабет", kk: "E23.2 — Қантсыз диабет", en: "E23.2 — Diabetes insipidus" },
    { ru: "E05.9 — Тиреотоксикоз", kk: "E05.9 — Тиреотоксикоз", en: "E05.9 — Thyrotoxicosis" },
    { ru: "N18.9 — Хроническая болезнь почек", kk: "N18.9 — Созылмалы бүйрек ауруы", en: "N18.9 — Chronic kidney disease" },
  ],
  cystitis_female: [
    { ru: "N30.0 — Острый неосложнённый цистит", kk: "N30.0 — Асқынбаған жедел цистит", en: "N30.0 — Acute uncomplicated cystitis" },
    { ru: "N10 — Острый пиелонефрит", kk: "N10 — Жедел пиелонефрит", en: "N10 — Acute pyelonephritis" },
    { ru: "N34.1 — Уретрит", kk: "N34.1 — Уретрит", en: "N34.1 — Urethritis" },
    { ru: "N23 — Почечная колика", kk: "N23 — Бүйрек шаншуы", en: "N23 — Renal colic" },
    { ru: "A54.0 — Гонококковая инфекция (ИППП)", kk: "A54.0 — Гонококк инфекциясы (ЖЖБИ)", en: "A54.0 — Gonococcal infection (STI)" },
  ],
  stable_angina: [
    { ru: "I20.9 — ИБС: стабильная стенокардия напряжения II ФК", kk: "I20.9 — ЖИА: II ФК тұрақты стенокардия", en: "I20.9 — CAD: stable exertional angina, NYHA/CCS FC II" },
    { ru: "I21 — Острый инфаркт миокарда", kk: "I21 — Жедел миокард инфарктісі", en: "I21 — Acute myocardial infarction" },
    { ru: "I20.0 — Нестабильная стенокардия", kk: "I20.0 — Тұрақсыз стенокардия", en: "I20.0 — Unstable angina" },
    { ru: "K21.9 — ГЭРБ (гастроэзофагеальная рефлюксная болезнь)", kk: "K21.9 — ГЭРА (гастроэзофагеальды рефлюкс ауруы)", en: "K21.9 — GERD (gastroesophageal reflux disease)" },
    { ru: "M54.6 — Межрёберная невралгия", kk: "M54.6 — Қабырғааралық невралгия", en: "M54.6 — Intercostal neuralgia" },
  ],
  heart_failure: [
    { ru: "I50.9 — Хроническая сердечная недостаточность II-III ФК", kk: "I50.9 — Созылмалы жүрек жеткіліксіздігі II-III ФК", en: "I50.9 — Chronic heart failure, FC II–III" },
    { ru: "J44.1 — ХОБЛ, обострение", kk: "J44.1 — СОЗТ, өршу", en: "J44.1 — COPD, exacerbation" },
    { ru: "N04 — Нефротический синдром", kk: "N04 — Нефротикалық синдром", en: "N04 — Nephrotic syndrome" },
    { ru: "I26 — Тромбоэмболия лёгочной артерии", kk: "I26 — Өкпе артериясының тромбоэмболиясы", en: "I26 — Pulmonary embolism" },
    { ru: "J18.9 — Внебольничная пневмония", kk: "J18.9 — Аурухана сыртылық пневмония", en: "J18.9 — Community-acquired pneumonia" },
  ],
  copd_exacerbation: [
    { ru: "J44.1 — ХОБЛ, обострение средней тяжести", kk: "J44.1 — СОЗТ, орташа ауырлықтағы өршу", en: "J44.1 — COPD, moderate exacerbation" },
    { ru: "J45.9 — Бронхиальная астма, обострение", kk: "J45.9 — Бронх демікпесі, өршу", en: "J45.9 — Bronchial asthma, exacerbation" },
    { ru: "J18.9 — Внебольничная пневмония", kk: "J18.9 — Аурухана сыртылық пневмония", en: "J18.9 — Community-acquired pneumonia" },
    { ru: "I50.9 — Сердечная недостаточность", kk: "I50.9 — Жүрек жеткіліксіздігі", en: "I50.9 — Heart failure" },
    { ru: "J81 — Отёк лёгких", kk: "J81 — Өкпе ісінуі", en: "J81 — Pulmonary edema" },
  ],
  hypothyroidism: [
    { ru: "E03.9 — Первичный гипотиреоз (на фоне АИТ)", kk: "E03.9 — АИТ фонындағы бастапқы гипотиреоз", en: "E03.9 — Primary hypothyroidism (due to autoimmune thyroiditis)" },
    { ru: "D50.9 — Железодефицитная анемия", kk: "D50.9 — Темір тапшылығы анемиясы", en: "D50.9 — Iron-deficiency anemia" },
    { ru: "F32.9 — Депрессивный эпизод", kk: "F32.9 — Депрессиялық эпизод", en: "F32.9 — Depressive episode" },
    { ru: "E66.9 — Ожирение", kk: "E66.9 — Семіздік", en: "E66.9 — Obesity" },
    { ru: "N18.9 — Хроническая болезнь почек", kk: "N18.9 — Созылмалы бүйрек ауруы", en: "N18.9 — Chronic kidney disease" },
  ],
  migraine: [
    { ru: "G43.0 — Мигрень без ауры, эпизодическая", kk: "G43.0 — Аурасыз мигрень, эпизодтық", en: "G43.0 — Migraine without aura, episodic" },
    { ru: "G44.2 — Головная боль напряжения", kk: "G44.2 — Кернеулі бас ауруы", en: "G44.2 — Tension-type headache" },
    { ru: "G44.0 — Кластерная головная боль", kk: "G44.0 — Кластерлік бас ауруы", en: "G44.0 — Cluster headache" },
    { ru: "I10 — Гипертоническая головная боль", kk: "I10 — Гипертониялық бас ауруы", en: "I10 — Hypertensive headache" },
    { ru: "G43.1 — Мигрень с аурой", kk: "G43.1 — Аурамен мигрень", en: "G43.1 — Migraine with aura" },
  ],
  peptic_ulcer: [
    { ru: "K25.9 — Язвенная болезнь желудка (H.pylori-ассоциированная)", kk: "K25.9 — H.pylori-байланысты асқазан ойық жарасы", en: "K25.9 — Peptic ulcer disease (H. pylori-associated)" },
    { ru: "K21.9 — ГЭРБ", kk: "K21.9 — ГЭРА", en: "K21.9 — GERD" },
    { ru: "K29.7 — Хронический гастрит", kk: "K29.7 — Созылмалы гастрит", en: "K29.7 — Chronic gastritis" },
    { ru: "K26.9 — Язвенная болезнь 12-перстной кишки", kk: "K26.9 — Ұлтабар ойық жарасы", en: "K26.9 — Duodenal ulcer, unspecified" },
    { ru: "C16.9 — Рак желудка", kk: "C16.9 — Асқазан қатерлі ісігі", en: "C16.9 — Gastric cancer, unspecified" },
  ],
  // ─── Cardiology (new) ──────────────────────────────────────
  atrial_fib: [
    { ru: "I48 — Фибрилляция предсердий, тахисистолическая форма", kk: "I48 — Жүрекшелер фибрилляциясы, тахисистолиялық", en: "I48 — Atrial fibrillation, tachysystolic form" },
    { ru: "I47.1 — Наджелудочковая тахикардия", kk: "I47.1 — Қарыншаүсті тахикардия", en: "I47.1 — Supraventricular tachycardia" },
    { ru: "I50.9 — Хроническая сердечная недостаточность", kk: "I50.9 — Созылмалы жүрек жеткіліксіздігі", en: "I50.9 — Chronic heart failure" },
    { ru: "I20.9 — ИБС: стабильная стенокардия", kk: "I20.9 — ЖИА: тұрақты стенокардия", en: "I20.9 — CAD: stable angina pectoris" },
    { ru: "E05.0 — Тиреотоксикоз", kk: "E05.0 — Тиреотоксикоз", en: "E05.0 — Thyrotoxicosis" },
  ],
  acute_mi: [
    { ru: "I21.0 — Острый передний инфаркт миокарда с подъёмом ST (STEMI)", kk: "I21.0 — ST көтерілуімен жедел алдыңғы миокард инфарктісі (STEMI)", en: "I21.0 — Acute anterior ST-elevation myocardial infarction (STEMI)" },
    { ru: "I20.0 — Нестабильная стенокардия", kk: "I20.0 — Тұрақсыз стенокардия", en: "I20.0 — Unstable angina" },
    { ru: "I26 — Тромбоэмболия лёгочной артерии", kk: "I26 — Өкпе артериясы тромбоэмболиясы", en: "I26 — Pulmonary embolism" },
    { ru: "K21.9 — ГЭРБ", kk: "K21.9 — ГЭРА", en: "K21.9 — GERD" },
    { ru: "I30 — Острый перикардит", kk: "I30 — Жедел перикардит", en: "I30 — Acute pericarditis" },
  ],
  hypertension_essential: [
    { ru: "I10 — Эссенциальная артериальная гипертензия 2 степени, риск ССО 3", kk: "I10 — 2 дәрежелі эссенциалды артериялық гипертензия, ЖҚА қаупі 3", en: "I10 — Essential arterial hypertension, grade 2, cardiovascular risk 3" },
    { ru: "I15.0 — Реноваскулярная гипертензия", kk: "I15.0 — Реноваскулярлы гипертензия", en: "I15.0 — Renovascular hypertension" },
    { ru: "E26 — Гиперальдостеронизм", kk: "E26 — Гиперальдостеронизм", en: "E26 — Hyperaldosteronism" },
    { ru: "E27.5 — Феохромоцитома", kk: "E27.5 — Феохромоцитома", en: "E27.5 — Pheochromocytoma" },
    { ru: "G44.2 — Головная боль напряжения", kk: "G44.2 — Кернеулі бас ауруы", en: "G44.2 — Tension-type headache" },
  ],
  unstable_angina: [
    { ru: "I20.0 — Нестабильная стенокардия (ОКС без подъёма ST)", kk: "I20.0 — Тұрақсыз стенокардия (ST көтерілуінсіз ЖКС)", en: "I20.0 — Unstable angina (ACS without ST elevation)" },
    { ru: "I21.4 — Острый инфаркт миокарда без подъёма ST (NSTEMI)", kk: "I21.4 — ST көтерілуінсіз жедел миокард инфарктісі (NSTEMI)", en: "I21.4 — Acute non-ST-elevation myocardial infarction (NSTEMI)" },
    { ru: "I20.9 — ИБС: стабильная стенокардия", kk: "I20.9 — ЖИА: тұрақты стенокардия", en: "I20.9 — CAD: stable angina pectoris" },
    { ru: "K21.9 — ГЭРБ", kk: "K21.9 — ГЭРА", en: "K21.9 — GERD" },
    { ru: "M54.6 — Межрёберная невралгия", kk: "M54.6 — Қабырғааралық невралгия", en: "M54.6 — Intercostal neuralgia" },
  ],
  dvt: [
    { ru: "I80.2 — Тромбоз глубоких вен правой нижней конечности", kk: "I80.2 — Оң аяқтың терең вена тромбозы", en: "I80.2 — Deep vein thrombosis of the right lower extremity" },
    { ru: "I83.9 — Варикозная болезнь нижних конечностей", kk: "I83.9 — Аяқтың варикозы", en: "I83.9 — Varicose veins of the lower extremities" },
    { ru: "L03.1 — Целлюлит голени", kk: "L03.1 — Балтыр целлюлиті", en: "L03.1 — Cellulitis of the lower leg" },
    { ru: "M76.6 — Тендинит ахиллова сухожилия", kk: "M76.6 — Ахилл сіңірінің тендиниті", en: "M76.6 — Achilles tendinitis" },
    { ru: "I87.0 — Постфлебитический синдром", kk: "I87.0 — Постфлебиттік синдром", en: "I87.0 — Post-thrombotic syndrome" },
  ],
  // ─── Endocrinology (new) ───────────────────────────────────
  dka_t1: [
    { ru: "E10.1 — Сахарный диабет 1 типа, дебют, кетоацидоз", kk: "E10.1 — 1 тип ҚД, дебюті, кетоацидоз", en: "E10.1 — Type 1 diabetes mellitus, new onset, with ketoacidosis" },
    { ru: "E11.0 — Сахарный диабет 2 типа, гиперосмолярное состояние", kk: "E11.0 — 2 тип ҚД, гиперосмолярлы күй", en: "E11.0 — Type 2 diabetes mellitus, hyperosmolar state" },
    { ru: "K85.9 — Острый панкреатит", kk: "K85.9 — Жедел панкреатит", en: "K85.9 — Acute pancreatitis, unspecified" },
    { ru: "K35.8 — Острый аппендицит", kk: "K35.8 — Жедел аппендицит", en: "K35.8 — Acute appendicitis" },
    { ru: "F50.0 — Нервная анорексия", kk: "F50.0 — Невроздық анорексия", en: "F50.0 — Anorexia nervosa" },
  ],
  graves: [
    { ru: "E05.0 — Диффузный токсический зоб (болезнь Грейвса)", kk: "E05.0 — Диффузды токсикалық жемсау (Грейвс)", en: "E05.0 — Diffuse toxic goiter (Graves' disease)" },
    { ru: "E05.1 — Токсическая аденома щитовидной железы", kk: "E05.1 — Қалқанша безінің токсикалық аденомасы", en: "E05.1 — Toxic adenoma of the thyroid gland" },
    { ru: "F41.1 — Генерализованное тревожное расстройство", kk: "F41.1 — Жалпылама мазасыздық бұзылысы", en: "F41.1 — Generalized anxiety disorder" },
    { ru: "F32.9 — Депрессивный эпизод", kk: "F32.9 — Депрессиялық эпизод", en: "F32.9 — Depressive episode" },
    { ru: "E66.9 — Снижение массы тела (необъяснимое)", kk: "E66.9 — Себепсіз салмақ жоғалу", en: "E66.9 — Unexplained weight loss" },
  ],
  metabolic_syndrome: [
    { ru: "E66.0 — Метаболический синдром", kk: "E66.0 — Метаболикалық синдром", en: "E66.0 — Metabolic syndrome" },
    { ru: "E11.9 — Сахарный диабет 2 типа", kk: "E11.9 — 2 тип ҚД", en: "E11.9 — Type 2 diabetes mellitus, unspecified" },
    { ru: "E78.5 — Гиперлипидемия неуточнённая", kk: "E78.5 — Гиперлипидемия", en: "E78.5 — Hyperlipidemia, unspecified" },
    { ru: "I10 — Артериальная гипертензия", kk: "I10 — Артериялық гипертензия", en: "I10 — Arterial hypertension" },
    { ru: "K76.0 — Неалкогольная жировая болезнь печени", kk: "K76.0 — Алкогольсіз бауырдың майлы ауруы", en: "K76.0 — Non-alcoholic fatty liver disease" },
  ],
  nodular_goiter: [
    { ru: "E04.1 — Узловой эутиреоидный зоб (солитарный узел)", kk: "E04.1 — Түйінді эутиреоидты жемсау (бір түйін)", en: "E04.1 — Euthyroid nodular goiter (solitary nodule)" },
    { ru: "C73 — Рак щитовидной железы", kk: "C73 — Қалқанша безі қатерлі ісігі", en: "C73 — Thyroid cancer" },
    { ru: "E05.1 — Токсическая аденома щитовидной железы", kk: "E05.1 — Токсикалық аденома", en: "E05.1 — Toxic adenoma of the thyroid gland" },
    { ru: "E04.2 — Многоузловой зоб", kk: "E04.2 — Көп түйінді жемсау", en: "E04.2 — Multinodular goiter" },
    { ru: "D34 — Доброкачественная опухоль щитовидной железы", kk: "D34 — Қалқанша безінің қатерсіз ісігі", en: "D34 — Benign neoplasm of the thyroid gland" },
  ],
  cushing_iatrogenic: [
    { ru: "E24.2 — Ятрогенный синдром Иценко-Кушинга", kk: "E24.2 — Ятрогенді Иценко-Кушинг синдромы", en: "E24.2 — Iatrogenic Cushing's syndrome" },
    { ru: "E24.0 — Болезнь Иценко-Кушинга (АКТГ-зависимый)", kk: "E24.0 — Иценко-Кушинг ауруы (АКТГ-тәуелді)", en: "E24.0 — Cushing's disease (ACTH-dependent)" },
    { ru: "E66.9 — Алиментарное ожирение", kk: "E66.9 — Алиментарлы семіздік", en: "E66.9 — Alimentary obesity" },
    { ru: "E03.9 — Гипотиреоз", kk: "E03.9 — Гипотиреоз", en: "E03.9 — Hypothyroidism" },
    { ru: "E27.5 — Феохромоцитома", kk: "E27.5 — Феохромоцитома", en: "E27.5 — Pheochromocytoma" },
  ],
  addison: [
    { ru: "E27.1 — Первичная надпочечниковая недостаточность (болезнь Аддисона)", kk: "E27.1 — Бастапқы бүйрек үсті безі жеткіліксіздігі (Аддисон)", en: "E27.1 — Primary adrenocortical insufficiency (Addison's disease)" },
    { ru: "E27.4 — Вторичная надпочечниковая недостаточность", kk: "E27.4 — Екіншілік бүйрек үсті безі жеткіліксіздігі", en: "E27.4 — Secondary adrenocortical insufficiency" },
    { ru: "E03.9 — Гипотиреоз", kk: "E03.9 — Гипотиреоз", en: "E03.9 — Hypothyroidism" },
    { ru: "D50.9 — Железодефицитная анемия", kk: "D50.9 — Темір тапшылығы анемиясы", en: "D50.9 — Iron-deficiency anemia" },
    { ru: "F32.9 — Депрессивный эпизод", kk: "F32.9 — Депрессиялық эпизод", en: "F32.9 — Depressive episode" },
  ],
  // ─── Gastroenterology (new) ────────────────────────────────
  acute_pancreatitis: [
    { ru: "K85.9 — Острый панкреатит, алкогольной этиологии", kk: "K85.9 — Жедел панкреатит, алкогольдік", en: "K85.9 — Acute pancreatitis, alcoholic etiology" },
    { ru: "K81.0 — Острый холецистит", kk: "K81.0 — Жедел холецистит", en: "K81.0 — Acute cholecystitis" },
    { ru: "K25.9 — Перфоративная язва желудка", kk: "K25.9 — Асқазан ойық жарасы тесілуі", en: "K25.9 — Perforated gastric ulcer" },
    { ru: "K56.6 — Кишечная непроходимость", kk: "K56.6 — Ішек өтімсіздігі", en: "K56.6 — Intestinal obstruction" },
    { ru: "I21 — Острый инфаркт миокарда (атипичная форма)", kk: "I21 — Жедел миокард инфарктісі", en: "I21 — Acute myocardial infarction (atypical presentation)" },
  ],
  acute_cholecystitis: [
    { ru: "K81.0 — Острый калькулёзный холецистит", kk: "K81.0 — Жедел калькулёзді холецистит", en: "K81.0 — Acute calculous cholecystitis" },
    { ru: "K80.5 — Желчная колика", kk: "K80.5 — Өт шаншуы", en: "K80.5 — Biliary colic" },
    { ru: "K85.9 — Острый панкреатит", kk: "K85.9 — Жедел панкреатит", en: "K85.9 — Acute pancreatitis, unspecified" },
    { ru: "K83.0 — Холангит", kk: "K83.0 — Холангит", en: "K83.0 — Cholangitis" },
    { ru: "K76.6 — Цирроз печени", kk: "K76.6 — Бауыр циррозы", en: "K76.6 — Liver cirrhosis" },
  ],
  gerd: [
    { ru: "K21.0 — Гастроэзофагеальная рефлюксная болезнь с эзофагитом", kk: "K21.0 — Эзофагитпен ГЭРА", en: "K21.0 — Gastroesophageal reflux disease with esophagitis" },
    { ru: "K25.9 — Язвенная болезнь желудка", kk: "K25.9 — Асқазан ойық жарасы", en: "K25.9 — Gastric ulcer, unspecified" },
    { ru: "K29.7 — Хронический гастрит", kk: "K29.7 — Созылмалы гастрит", en: "K29.7 — Chronic gastritis" },
    { ru: "I20.9 — Стабильная стенокардия", kk: "I20.9 — Тұрақты стенокардия", en: "I20.9 — Stable angina pectoris" },
    { ru: "K22.4 — Дискинезия пищевода", kk: "K22.4 — Өңеш дискинезиясы", en: "K22.4 — Esophageal dysmotility" },
  ],
  ibs_d: [
    { ru: "K58.0 — Синдром раздражённого кишечника с диареей", kk: "K58.0 — Диареямен ішектің тітіркену синдромы", en: "K58.0 — Irritable bowel syndrome with diarrhea" },
    { ru: "K50.0 — Болезнь Крона тонкой кишки", kk: "K50.0 — Жіңішке ішек Крон ауруы", en: "K50.0 — Crohn's disease of the small intestine" },
    { ru: "K51.0 — Язвенный колит", kk: "K51.0 — Жаралы колит", en: "K51.0 — Ulcerative colitis" },
    { ru: "K90.0 — Целиакия", kk: "K90.0 — Целиакия", en: "K90.0 — Celiac disease" },
    { ru: "A09 — Инфекционный гастроэнтерит", kk: "A09 — Жұқпалы гастроэнтерит", en: "A09 — Infectious gastroenteritis" },
  ],
  uc_flare: [
    { ru: "K51.0 — Язвенный колит, обострение средней тяжести", kk: "K51.0 — Жаралы колит, орташа өршу", en: "K51.0 — Ulcerative colitis, moderate-severity exacerbation" },
    { ru: "K50.1 — Болезнь Крона толстой кишки", kk: "K50.1 — Тоқ ішек Крон ауруы", en: "K50.1 — Crohn's disease of the large intestine" },
    { ru: "A09 — Инфекционный колит", kk: "A09 — Жұқпалы колит", en: "A09 — Infectious colitis" },
    { ru: "A06.1 — Амёбиаз", kk: "A06.1 — Амёбиаз", en: "A06.1 — Amebiasis" },
    { ru: "K57 — Дивертикулёз с кровотечением", kk: "K57 — Дивертикулёз қан кетумен", en: "K57 — Diverticulosis with bleeding" },
  ],
  hep_a: [
    { ru: "B15.9 — Острый вирусный гепатит A", kk: "B15.9 — Жедел вирусты гепатит A", en: "B15.9 — Acute viral hepatitis A" },
    { ru: "B16 — Острый вирусный гепатит B", kk: "B16 — Жедел вирусты гепатит B", en: "B16 — Acute viral hepatitis B" },
    { ru: "K71 — Токсический гепатит", kk: "K71 — Токсикалық гепатит", en: "K71 — Toxic hepatitis" },
    { ru: "K80.5 — Желчная колика с холестазом", kk: "K80.5 — Холестаз бен өт шаншуы", en: "K80.5 — Biliary colic with cholestasis" },
    { ru: "B27.0 — Инфекционный мононуклеоз", kk: "B27.0 — Жұқпалы мононуклеоз", en: "B27.0 — Infectious mononucleosis" },
  ],
  // ─── Infectious (new) ──────────────────────────────────────
  salmonellosis: [
    { ru: "A02.0 — Сальмонеллёзный гастроэнтерит", kk: "A02.0 — Сальмонеллёзды гастроэнтерит", en: "A02.0 — Salmonella gastroenteritis" },
    { ru: "A04.5 — Кампилобактериоз", kk: "A04.5 — Кампилобактериоз", en: "A04.5 — Campylobacteriosis" },
    { ru: "A08.0 — Ротавирусный гастроэнтерит", kk: "A08.0 — Ротавирусты гастроэнтерит", en: "A08.0 — Rotavirus gastroenteritis" },
    { ru: "A03 — Шигеллёз (дизентерия)", kk: "A03 — Шигеллёз (дизентерия)", en: "A03 — Shigellosis (dysentery)" },
    { ru: "K52.9 — Неинфекционный гастроэнтерит", kk: "K52.9 — Жұқпалы емес гастроэнтерит", en: "K52.9 — Noninfective gastroenteritis" },
  ],
  typhoid: [
    { ru: "A01.0 — Брюшной тиф", kk: "A01.0 — Іш сүзегі", en: "A01.0 — Typhoid fever" },
    { ru: "A23.9 — Бруцеллёз", kk: "A23.9 — Бруцеллёз", en: "A23.9 — Brucellosis" },
    { ru: "B50 — Малярия", kk: "B50 — Безгек", en: "B50 — Malaria" },
    { ru: "A39 — Менингококковая инфекция", kk: "A39 — Менингококк инфекциясы", en: "A39 — Meningococcal infection" },
    { ru: "A75 — Сыпной тиф", kk: "A75 — Бөртпелі сүзек", en: "A75 — Typhus fever" },
  ],
  rotavirus: [
    { ru: "A08.0 — Ротавирусный гастроэнтерит", kk: "A08.0 — Ротавирусты гастроэнтерит", en: "A08.0 — Rotavirus gastroenteritis" },
    { ru: "A02.0 — Сальмонеллёзный гастроэнтерит", kk: "A02.0 — Сальмонеллёзды гастроэнтерит", en: "A02.0 — Salmonella gastroenteritis" },
    { ru: "A08.4 — Норовирусный гастроэнтерит", kk: "A08.4 — Норовирусты гастроэнтерит", en: "A08.4 — Norovirus gastroenteritis" },
    { ru: "K59.1 — Функциональная диарея", kk: "K59.1 — Функционалды диарея", en: "K59.1 — Functional diarrhea" },
    { ru: "K52.2 — Аллергический гастроэнтерит", kk: "K52.2 — Аллергиялық гастроэнтерит", en: "K52.2 — Allergic gastroenteritis" },
  ],
  erysipelas: [
    { ru: "A46 — Рожистое воспаление правой голени", kk: "A46 — Оң балтырдың тілмесауы", en: "A46 — Erysipelas of the right lower leg" },
    { ru: "L03.1 — Целлюлит нижней конечности", kk: "L03.1 — Аяқ целлюлиті", en: "L03.1 — Cellulitis of the lower extremity" },
    { ru: "I80.2 — Тромбоз глубоких вен", kk: "I80.2 — Терең вена тромбозы", en: "I80.2 — Deep vein thrombosis" },
    { ru: "L08.0 — Пиодермия", kk: "L08.0 — Пиодермия", en: "L08.0 — Pyoderma" },
    { ru: "M72.6 — Некротизирующий фасциит", kk: "M72.6 — Некроздаушы фасциит", en: "M72.6 — Necrotizing fasciitis" },
  ],
  chickenpox_adult: [
    { ru: "B01.9 — Ветряная оспа у взрослого", kk: "B01.9 — Ересектердегі суқатер", en: "B01.9 — Varicella (chickenpox) in an adult" },
    { ru: "B02 — Опоясывающий лишай (Herpes zoster)", kk: "B02 — Белдеуленген теміреткі", en: "B02 — Herpes zoster" },
    { ru: "A38 — Скарлатина", kk: "A38 — Скарлатина", en: "A38 — Scarlet fever" },
    { ru: "B05 — Корь", kk: "B05 — Қызылша", en: "B05 — Measles" },
    { ru: "L27.0 — Лекарственная сыпь", kk: "L27.0 — Дәрілік бөртпе", en: "L27.0 — Drug-induced rash" },
  ],
  mononucleosis: [
    { ru: "B27.0 — Инфекционный мононуклеоз (EBV)", kk: "B27.0 — Жұқпалы мононуклеоз (EBV)", en: "B27.0 — Infectious mononucleosis (EBV)" },
    { ru: "J03.9 — Острый тонзиллит (стрептококковый)", kk: "J03.9 — Жедел тонзиллит", en: "J03.9 — Acute tonsillitis (streptococcal)" },
    { ru: "B58 — Токсоплазмоз", kk: "B58 — Токсоплазмоз", en: "B58 — Toxoplasmosis" },
    { ru: "B20 — ВИЧ-инфекция, острая фаза", kk: "B20 — АИВ-инфекция, жедел фаза", en: "B20 — HIV infection, acute phase" },
    { ru: "C81 — Лимфома Ходжкина", kk: "C81 — Ходжкин лимфомасы", en: "C81 — Hodgkin lymphoma" },
  ],
  // ─── Neurology (new) ───────────────────────────────────────
  ischemic_stroke: [
    { ru: "I63.9 — Острый ишемический инсульт (кардиоэмболический)", kk: "I63.9 — Жедел ишемиялық инсульт (кардиоэмболдық)", en: "I63.9 — Acute ischemic stroke (cardioembolic)" },
    { ru: "I61 — Внутримозговое кровоизлияние", kk: "I61 — Ми ішілік қан құйылу", en: "I61 — Intracerebral hemorrhage" },
    { ru: "G45.9 — Транзиторная ишемическая атака", kk: "G45.9 — Транзиторлы ишемиялық шабуыл", en: "G45.9 — Transient ischemic attack" },
    { ru: "G40.3 — Эпилептический припадок", kk: "G40.3 — Эпилепсиялық ұстама", en: "G40.3 — Epileptic seizure" },
    { ru: "F44.4 — Конверсионное расстройство", kk: "F44.4 — Конверсиялық бұзылыс", en: "F44.4 — Conversion disorder" },
  ],
  epilepsy_gtcs: [
    { ru: "G40.3 — Идиопатическая генерализованная эпилепсия с ТКП", kk: "G40.3 — ТКҰ-мен идиопатиялық жалпылама эпилепсия", en: "G40.3 — Idiopathic generalized epilepsy with tonic-clonic seizures" },
    { ru: "R56.0 — Фебрильные судороги", kk: "R56.0 — Фебрильді ұстамалар", en: "R56.0 — Febrile seizures" },
    { ru: "F44.5 — Психогенный неэпилептический припадок", kk: "F44.5 — Психогенді эпилепсиялық емес ұстама", en: "F44.5 — Psychogenic non-epileptic seizure" },
    { ru: "R55 — Обморок (синкопа)", kk: "R55 — Талу (синкоп)", en: "R55 — Syncope" },
    { ru: "E16.2 — Гипогликемический припадок", kk: "E16.2 — Гипогликемиялық ұстама", en: "E16.2 — Hypoglycemic seizure" },
  ],
  tension_headache: [
    { ru: "G44.2 — Хроническая головная боль напряжения", kk: "G44.2 — Созылмалы кернеулі бас ауруы", en: "G44.2 — Chronic tension-type headache" },
    { ru: "G43.0 — Мигрень без ауры", kk: "G43.0 — Аурасыз мигрень", en: "G43.0 — Migraine without aura" },
    { ru: "G44.4 — Медикаментозно-индуцированная головная боль", kk: "G44.4 — Дәрілік-индукцияланған бас ауруы", en: "G44.4 — Medication-overuse headache" },
    { ru: "I10 — Гипертоническая головная боль", kk: "I10 — Гипертониялық бас ауруы", en: "I10 — Hypertensive headache" },
    { ru: "M53.0 — Цервикогенная головная боль", kk: "M53.0 — Цервикогенді бас ауруы", en: "M53.0 — Cervicogenic headache" },
  ],
  cervical_radiculopathy: [
    { ru: "M50.1 — Цервикальная радикулопатия C7 (дискогенная)", kk: "M50.1 — C7 цервикалды радикулопатия (дискогенді)", en: "M50.1 — Cervical radiculopathy C7 (discogenic)" },
    { ru: "M54.2 — Цервикалгия (механическая)", kk: "M54.2 — Цервикалгия", en: "M54.2 — Cervicalgia (mechanical)" },
    { ru: "M75.1 — Синдром ротаторной манжеты плеча", kk: "M75.1 — Иық ротатор манжетасы синдромы", en: "M75.1 — Rotator cuff syndrome" },
    { ru: "G56.0 — Синдром запястного канала", kk: "G56.0 — Кәрі жілік арна синдромы", en: "G56.0 — Carpal tunnel syndrome" },
    { ru: "M53.1 — Шейно-плечевой синдром", kk: "M53.1 — Мойын-иық синдромы", en: "M53.1 — Cervicobrachial syndrome" },
  ],
  diabetic_neuropathy: [
    { ru: "G63.2 — Дистальная симметричная диабетическая полиневропатия", kk: "G63.2 — Дистальды симметриялы диабеттік полиневропатия", en: "G63.2 — Distal symmetric diabetic polyneuropathy" },
    { ru: "G62.1 — Алкогольная полиневропатия", kk: "G62.1 — Алкогольдік полиневропатия", en: "G62.1 — Alcoholic polyneuropathy" },
    { ru: "G62.9 — Полиневропатия, не уточнённая", kk: "G62.9 — Полиневропатия", en: "G62.9 — Polyneuropathy, unspecified" },
    { ru: "I73.9 — Облитерирующий атеросклероз нижних конечностей", kk: "I73.9 — Аяқтың облитерациялаушы атеросклерозы", en: "I73.9 — Peripheral arterial occlusive disease of the lower extremities" },
    { ru: "M54.5 — Поясничная боль", kk: "M54.5 — Бел ауруы", en: "M54.5 — Low back pain" },
  ],
  bell_palsy: [
    { ru: "G51.0 — Паралич Белла (идиопатическая невропатия лицевого нерва)", kk: "G51.0 — Белл сал ауруы", en: "G51.0 — Bell's palsy (idiopathic facial nerve neuropathy)" },
    { ru: "B02.2 — Синдром Рамсея-Ханта (Herpes zoster)", kk: "B02.2 — Рамсей-Хант синдромы", en: "B02.2 — Ramsay Hunt syndrome (Herpes zoster)" },
    { ru: "I63.9 — Ишемический инсульт", kk: "I63.9 — Ишемиялық инсульт", en: "I63.9 — Ischemic stroke" },
    { ru: "G70.0 — Миастения", kk: "G70.0 — Миастения", en: "G70.0 — Myasthenia gravis" },
    { ru: "C70 — Опухоль ЦНС", kk: "C70 — ОЖЖ ісігі", en: "C70 — CNS tumor" },
  ],
  // ─── Pulmonology (new) ─────────────────────────────────────
  asthma_exacerbation: [
    { ru: "J45.0 — Бронхиальная астма, обострение средней тяжести", kk: "J45.0 — Бронх демікпесі, орташа өршу", en: "J45.0 — Bronchial asthma, moderate exacerbation" },
    { ru: "J44.1 — ХОБЛ, обострение", kk: "J44.1 — СОЗТ, өршу", en: "J44.1 — COPD, exacerbation" },
    { ru: "J20.9 — Острый бронхит", kk: "J20.9 — Жедел бронхит", en: "J20.9 — Acute bronchitis" },
    { ru: "J81 — Отёк лёгких", kk: "J81 — Өкпе ісінуі", en: "J81 — Pulmonary edema" },
    { ru: "R06.5 — Гипервентиляционный синдром", kk: "R06.5 — Гипервентиляциялық синдром", en: "R06.5 — Hyperventilation syndrome" },
  ],
  tb_lung: [
    { ru: "A15.0 — Инфильтративный туберкулёз с распадом, МБТ+", kk: "A15.0 — Инфильтративті туберкулез ыдыраумен, ТМБ+", en: "A15.0 — Infiltrative pulmonary tuberculosis with cavitation, AFB+" },
    { ru: "J18.9 — Внебольничная пневмония", kk: "J18.9 — Аурухана сыртылық пневмония", en: "J18.9 — Community-acquired pneumonia" },
    { ru: "C34 — Рак лёгкого", kk: "C34 — Өкпе қатерлі ісігі", en: "C34 — Lung cancer" },
    { ru: "B44.9 — Аспергиллёз лёгких", kk: "B44.9 — Өкпе аспергиллёзы", en: "B44.9 — Pulmonary aspergillosis" },
    { ru: "J44.1 — ХОБЛ, обострение", kk: "J44.1 — СОЗТ, өршу", en: "J44.1 — COPD, exacerbation" },
  ],
  acute_bronchitis: [
    { ru: "J20.9 — Острый бронхит, вирусной этиологии", kk: "J20.9 — Жедел бронхит, вирустық", en: "J20.9 — Acute bronchitis, viral etiology" },
    { ru: "J18.9 — Внебольничная пневмония", kk: "J18.9 — Аурухана сыртылық пневмония", en: "J18.9 — Community-acquired pneumonia" },
    { ru: "J06.9 — ОРВИ", kk: "J06.9 — ЖРВИ", en: "J06.9 — URI" },
    { ru: "J45.0 — Бронхиальная астма", kk: "J45.0 — Бронх демікпесі", en: "J45.0 — Bronchial asthma" },
    { ru: "A37.9 — Коклюш", kk: "A37.9 — Көкжөтел", en: "A37.9 — Pertussis (whooping cough)" },
  ],
  pulmonary_embolism: [
    { ru: "I26.9 — Тромбоэмболия лёгочной артерии, intermediate risk", kk: "I26.9 — Өкпе артериясы тромбоэмболиясы", en: "I26.9 — Pulmonary embolism, intermediate risk" },
    { ru: "I21 — Острый инфаркт миокарда", kk: "I21 — Жедел миокард инфарктісі", en: "I21 — Acute myocardial infarction" },
    { ru: "J18.9 — Внебольничная пневмония", kk: "J18.9 — Аурухана сыртылық пневмония", en: "J18.9 — Community-acquired pneumonia" },
    { ru: "J93.1 — Спонтанный пневмоторакс", kk: "J93.1 — Стихиялы пневмоторакс", en: "J93.1 — Spontaneous pneumothorax" },
    { ru: "I50.9 — Острая сердечная недостаточность", kk: "I50.9 — Жедел жүрек жеткіліксіздігі", en: "I50.9 — Acute heart failure" },
  ],
  pleural_effusion: [
    { ru: "J90 — Правосторонний плевральный выпот (транссудат, ХСН)", kk: "J90 — Оң жақты плевралды экссудация (транссудат, СЖЖ)", en: "J90 — Right-sided pleural effusion (transudate, CHF)" },
    { ru: "C78.2 — Метастазы в плевре", kk: "C78.2 — Плевра метастаздары", en: "C78.2 — Pleural metastases" },
    { ru: "A15.6 — Туберкулёзный плеврит", kk: "A15.6 — Туберкулезді плеврит", en: "A15.6 — Tuberculous pleuritis" },
    { ru: "J86 — Эмпиема плевры", kk: "J86 — Плевра эмпиемасы", en: "J86 — Pleural empyema" },
    { ru: "I50.9 — Хроническая сердечная недостаточность", kk: "I50.9 — Созылмалы жүрек жеткіліксіздігі", en: "I50.9 — Chronic heart failure" },
  ],
  pneumothorax: [
    { ru: "J93.1 — Спонтанный первичный пневмоторакс справа", kk: "J93.1 — Оң жақты бастапқы стихиялы пневмоторакс", en: "J93.1 — Primary spontaneous pneumothorax, right-sided" },
    { ru: "I26.9 — Тромбоэмболия лёгочной артерии", kk: "I26.9 — Өкпе артериясы тромбоэмболиясы", en: "I26.9 — Pulmonary embolism" },
    { ru: "J18.9 — Пневмония", kk: "J18.9 — Пневмония", en: "J18.9 — Pneumonia" },
    { ru: "J45.0 — Острый приступ бронхиальной астмы", kk: "J45.0 — Бронх демікпесінің жедел ұстамасы", en: "J45.0 — Acute asthma attack" },
    { ru: "M54.6 — Межрёберная невралгия", kk: "M54.6 — Қабырғааралық невралгия", en: "M54.6 — Intercostal neuralgia" },
  ],
};

/* ── Medication formulary (shared) ──────────────────────────── */

export interface FormularyCategory { id: string; ru: string; kk: string; en: string }

export const FORMULARY_CATEGORIES: FormularyCategory[] = [
  { id: "abx",    ru: "Антибиотики",    kk: "Антибиотиктер", en: "Antibiotics" },
  { id: "pain",   ru: "Анальгетики/НПВП", kk: "Анальгетиктер/ҚҚСП", en: "Analgesics / NSAIDs" },
  { id: "cardio", ru: "Кардиология",    kk: "Кардиология", en: "Cardiology" },
  { id: "resp",   ru: "Дыхательная",    kk: "Тыныс жүйесі", en: "Respiratory" },
  { id: "gi",     ru: "ЖКТ",            kk: "АІЖ", en: "GI tract" },
  { id: "endo",   ru: "Эндокринология", kk: "Эндокринология", en: "Endocrinology" },
  { id: "other",  ru: "Прочее",         kk: "Басқа", en: "Other" },
];

export interface Med { id: string; name: string; cat: string; note: Bi }

export const FORMULARY: Med[] = [
  // Antibiotics
  { id: "amox_clav", name: "Амоксициллин/клавуланат 875/125 мг", cat: "abx", note: { ru: "Защищённый пенициллин · табл", kk: "Қорғалған пенициллин · табл", en: "Protected penicillin · tab" } },
  { id: "azithro",   name: "Азитромицин 500 мг",          cat: "abx", note: { ru: "Макролид · табл", kk: "Макролид · табл", en: "Macrolide · tab" } },
  { id: "clarithro", name: "Кларитромицин 500 мг",        cat: "abx", note: { ru: "Макролид · эрадикация H.pylori", kk: "Макролид · H.pylori эрадикациясы", en: "Macrolide · H. pylori eradication" } },
  { id: "ceftriax",  name: "Цефтриаксон 1 г",             cat: "abx", note: { ru: "Цефалоспорин III · в/в, в/м", kk: "III буын цефалоспорин · к/т", en: "3rd-generation cephalosporin · IV, IM" } },
  { id: "cefurox",   name: "Цефуроксим 500 мг",           cat: "abx", note: { ru: "Цефалоспорин II · табл", kk: "II буын цефалоспорин · табл", en: "2nd-generation cephalosporin · tab" } },
  { id: "levoflox",  name: "Левофлоксацин 500 мг",        cat: "abx", note: { ru: "Респираторный фторхинолон · табл", kk: "Тыныс фторхинолоны · табл", en: "Respiratory fluoroquinolone · tab" } },
  { id: "doxy",      name: "Доксициклин 100 мг",          cat: "abx", note: { ru: "Тетрациклин · капс", kk: "Тетрациклин · капс", en: "Tetracycline · cap" } },
  { id: "rifampin",  name: "Рифампицин 300 мг",           cat: "abx", note: { ru: "Антибиотик-рифамицин · капс", kk: "Рифамицин антибиотигі · капс", en: "Rifamycin antibiotic · cap" } },
  { id: "nitrofur",  name: "Нитрофурантоин 100 мг",       cat: "abx", note: { ru: "Уроантисептик · капс", kk: "Уроантисептик · капс", en: "Urinary antiseptic · cap" } },
  { id: "fosfo",     name: "Фосфомицин 3 г",              cat: "abx", note: { ru: "Уроантибиотик · пакетик", kk: "Уроантибиотик · пакет", en: "Urinary antibiotic · sachet" } },
  // Analgesics / NSAID
  { id: "paracetamol", name: "Парацетамол 500 мг",        cat: "pain", note: { ru: "Анальгетик-антипиретик · табл", kk: "Анальгетик-антипиретик · табл", en: "Analgesic-antipyretic · tab" } },
  { id: "ibuprofen",   name: "Ибупрофен 400 мг",          cat: "pain", note: { ru: "НПВП · табл", kk: "ҚҚСП · табл", en: "NSAID · tab" } },
  { id: "ketorolac",   name: "Кеторолак 10 мг",           cat: "pain", note: { ru: "НПВП · табл", kk: "ҚҚСП · табл", en: "NSAID · tab" } },
  { id: "diclofenac",  name: "Диклофенак 50 мг",          cat: "pain", note: { ru: "НПВП · табл", kk: "ҚҚСП · табл", en: "NSAID · tab" } },
  // Cardiology
  { id: "enalapril",  name: "Эналаприл 10 мг",            cat: "cardio", note: { ru: "Ингибитор АПФ · табл", kk: "АӨФ тежегіші · табл", en: "ACE inhibitor · tab" } },
  { id: "amlodipine", name: "Амлодипин 5 мг",             cat: "cardio", note: { ru: "Антагонист кальция · табл", kk: "Кальций антагонисі · табл", en: "Calcium channel blocker · tab" } },
  { id: "bisoprolol", name: "Бисопролол 5 мг",            cat: "cardio", note: { ru: "Бета-адреноблокатор · табл", kk: "Бета-блокатор · табл", en: "Beta-blocker · tab" } },
  { id: "nifedipine", name: "Нифедипин 10 мг",            cat: "cardio", note: { ru: "Антагонист кальция · табл", kk: "Кальций антагонисі · табл", en: "Calcium channel blocker · tab" } },
  { id: "furosemide", name: "Фуросемид 40 мг",            cat: "cardio", note: { ru: "Петлевой диуретик · табл", kk: "Ілмекті диуретик · табл", en: "Loop diuretic · tab" } },
  { id: "spirono",    name: "Спиронолактон 25 мг",        cat: "cardio", note: { ru: "Калийсберегающий диуретик · табл", kk: "Калий сақтаушы диуретик · табл", en: "Potassium-sparing diuretic · tab" } },
  { id: "nitro",      name: "Нитроглицерин 0.5 мг",       cat: "cardio", note: { ru: "Нитрат · под язык", kk: "Нитрат · тіл астына", en: "Nitrate · sublingual" } },
  { id: "aspirin",    name: "Ацетилсалициловая к-та 75 мг", cat: "cardio", note: { ru: "Антиагрегант · табл", kk: "Антиагрегант · табл", en: "Antiplatelet agent · tab" } },
  { id: "atorva",     name: "Аторвастатин 20 мг",         cat: "cardio", note: { ru: "Статин · табл", kk: "Статин · табл", en: "Statin · tab" } },
  // Respiratory
  { id: "salbutamol",  name: "Сальбутамол",               cat: "resp", note: { ru: "Бета-2-агонист (КДБА) · ингалятор", kk: "Бета-2-агонист (ҚӘБА) · ингалятор", en: "Beta-2 agonist (SABA) · inhaler" } },
  { id: "ipratropium", name: "Ипратропия бромид",         cat: "resp", note: { ru: "Холинолитик · ингалятор", kk: "Холинолитик · ингалятор", en: "Anticholinergic · inhaler" } },
  { id: "bud_form",    name: "Будесонид/формотерол",      cat: "resp", note: { ru: "ИГКС + ДДБА · ингалятор", kk: "ИГКС + ҰӘБА · ингалятор", en: "ICS + LABA · inhaler" } },
  { id: "ambroxol",    name: "Амброксол 30 мг",           cat: "resp", note: { ru: "Муколитик · табл", kk: "Муколитик · табл", en: "Mucolytic · tab" } },
  { id: "prednisolone", name: "Преднизолон 5 мг",         cat: "resp", note: { ru: "Глюкокортикостероид · табл", kk: "Глюкокортикостероид · табл", en: "Glucocorticosteroid · tab" } },
  // GI
  { id: "omeprazole",  name: "Омепразол 20 мг",           cat: "gi", note: { ru: "Ингибитор протонной помпы · капс", kk: "Протон помпасының тежегіші · капс", en: "Proton pump inhibitor · cap" } },
  { id: "bismuth",     name: "Висмута трикалия дицитрат 120 мг", cat: "gi", note: { ru: "Гастропротектор · табл", kk: "Гастропротектор · табл", en: "Gastroprotective agent · tab" } },
  { id: "drotaverine", name: "Дротаверин 40 мг",          cat: "gi", note: { ru: "Спазмолитик · табл", kk: "Спазмолитик · табл", en: "Antispasmodic · tab" } },
  { id: "metoclopramide", name: "Метоклопрамид 10 мг",    cat: "gi", note: { ru: "Противорвотное · табл", kk: "Құсуға қарсы · табл", en: "Antiemetic · tab" } },
  // Endocrinology
  { id: "metformin",   name: "Метформин 1000 мг",         cat: "endo", note: { ru: "Бигуанид · табл", kk: "Бигуанид · табл", en: "Biguanide · tab" } },
  { id: "gliclazide",  name: "Гликлазид 60 мг",           cat: "endo", note: { ru: "Производное сульфонилмочевины · табл", kk: "Сульфонилмочевина туындысы · табл", en: "Sulfonylurea derivative · tab" } },
  { id: "insulin",     name: "Инсулин (базальный)",       cat: "endo", note: { ru: "Гормон · п/к инъекции", kk: "Гормон · т/а егу", en: "Hormone · SC injection" } },
  { id: "levothyroxine", name: "Левотироксин 50 мкг",     cat: "endo", note: { ru: "Гормон щитовидной железы · табл", kk: "Қалқанша безі гормоны · табл", en: "Thyroid hormone · tab" } },
  // Other
  { id: "oseltamivir", name: "Осельтамивир 75 мг",        cat: "other", note: { ru: "Противовирусный (грипп) · капс", kk: "Вирусқа қарсы (тұмау) · капс", en: "Antiviral (influenza) · cap" } },
  { id: "sumatriptan", name: "Суматриптан 50 мг",         cat: "other", note: { ru: "Триптан (мигрень) · табл", kk: "Триптан (мигрень) · табл", en: "Triptan (migraine) · tab" } },
  { id: "ferrous",     name: "Железа сульфат 100 мг",     cat: "other", note: { ru: "Препарат железа · табл", kk: "Темір препараты · табл", en: "Iron preparation · tab" } },
  { id: "rehydron",    name: "Регидрон",                  cat: "other", note: { ru: "Раствор для регидратации · пакетик", kk: "Регидратация ерітіндісі · пакет", en: "Oral rehydration solution · sachet" } },
  { id: "xylometazoline", name: "Ксилометазолин",         cat: "other", note: { ru: "Деконгестант · спрей", kk: "Деконгестант · спрей", en: "Decongestant · spray" } },
];

/* ── Physical examination (vitals + findings) ───────────────── */

export const VITALS_META: { key: keyof Vitals; label: string; unit: string }[] = [
  { key: "hr",   label: "ЧСС",  unit: "уд/мин" },
  { key: "bp",   label: "АД",   unit: "мм рт.ст." },
  { key: "spo2", label: "SpO₂", unit: "%" },
  { key: "temp", label: "t°",   unit: "°C" },
  { key: "rr",   label: "ЧДД",  unit: "/мин" },
];

export interface Vitals { hr: string; bp: string; spo2: string; temp: string; rr: string }

export interface ExamData {
  vitals: Vitals;
  abnormal: (keyof Vitals)[];
  inspection: Bi;
  auscultation: Bi;
  palpation: Bi;
  percussion: Bi;
}

export const EXAM_DATA: Record<string, ExamData> = {
  arvi_adult: {
    vitals: { hr: "88", bp: "118/76", spo2: "98", temp: "37.8", rr: "16" },
    abnormal: ["temp"],
    inspection: { ru: "Лёгкое недомогание, зев умеренно гиперемирован, насморк.", kk: "Жеңіл әлсіздік, жұтқыншақ гиперемиясы, мұрын ағуы.", en: "Mild malaise, throat moderately hyperemic, rhinorrhea." },
    auscultation: { ru: "Дыхание везикулярное, хрипов нет. Тоны сердца ясные.", kk: "Тыныс везикулалық, сырыл жоқ. Жүрек тондары анық.", en: "Breath sounds vesicular, no wheezes. Heart sounds clear." },
    palpation: { ru: "Живот мягкий, безболезненный. Подчелюстные л/у слегка увеличены.", kk: "Іш жұмсақ, ауырсынусыз. Жақ асты лимфа түйіндері сәл ұлғайған.", en: "Abdomen soft, non-tender. Submandibular lymph nodes slightly enlarged." },
    percussion: { ru: "Лёгочный звук ясный над всей поверхностью.", kk: "Өкпе дыбысы барлық жерде анық.", en: "Clear percussion note over all lung fields." },
  },
  pneumonia_community: {
    vitals: { hr: "104", bp: "120/75", spo2: "92", temp: "39.2", rr: "24" },
    abnormal: ["hr", "spo2", "temp", "rr"],
    inspection: { ru: "Состояние средней тяжести, кожа бледная, потливость.", kk: "Жағдайы орташа ауыр, тері бозарған, терлеу.", en: "Moderate general condition, skin pale, diaphoresis." },
    auscultation: { ru: "Справа в нижних отделах ослабленное дыхание, мелкопузырчатые хрипы, крепитация. Тахикардия.", kk: "Оң жақ төменгі бөлікте тыныс әлсіреген, ұсақ көпіршікті сырылдар, крепитация. Тахикардия.", en: "Diminished breath sounds at right lower lobe, fine crackles, crepitation. Tachycardia." },
    palpation: { ru: "Живот мягкий, безболезненный. Усиление голосового дрожания справа.", kk: "Іш жұмсақ, ауырсынусыз. Оң жақта дауыс дірілі күшейген.", en: "Abdomen soft, non-tender. Increased vocal fremitus on the right." },
    percussion: { ru: "Притупление перкуторного звука в нижних отделах справа.", kk: "Оң жақ төменгі бөлікте перкуссия дыбысы тұйықталған.", en: "Dullness to percussion in the right lower zone." },
  },
  brucellosis: {
    vitals: { hr: "96", bp: "115/70", spo2: "98", temp: "38.6", rr: "18" },
    abnormal: ["temp"],
    inspection: { ru: "Повышенная потливость, увеличение периферических лимфоузлов.", kk: "Терлеу жоғары, шеткі лимфа түйіндері ұлғайған.", en: "Increased sweating, peripheral lymphadenopathy." },
    auscultation: { ru: "Дыхание везикулярное. Тоны сердца приглушены, ритмичные.", kk: "Тыныс везикулалық. Жүрек тондары тұйық, ырғақты.", en: "Breath sounds vesicular. Heart sounds muffled, regular rhythm." },
    palpation: { ru: "Печень и селезёнка увеличены. Болезненность крупных суставов.", kk: "Бауыр мен көкбауыр ұлғайған. Ірі буындар ауырсынады.", en: "Hepatosplenomegaly. Tenderness of large joints." },
    percussion: { ru: "Границы печени расширены.", kk: "Бауыр шекаралары кеңейген.", en: "Liver borders enlarged." },
  },
  iron_deficiency_anemia: {
    vitals: { hr: "98", bp: "105/65", spo2: "98", temp: "36.6", rr: "18" },
    abnormal: ["hr"],
    inspection: { ru: "Выраженная бледность кожи и слизистых, ломкость ногтей, заеды в углах рта.", kk: "Тері мен шырышты қабаттың бозаруы, тырнақ сынғыштығы, ауыз бұрышында жара.", en: "Marked pallor of skin and mucous membranes, brittle nails, angular cheilitis." },
    auscultation: { ru: "Дыхание везикулярное. Мягкий систолический шум на верхушке сердца.", kk: "Тыныс везикулалық. Жүрек ұшында жұмсақ систолалық шу.", en: "Breath sounds vesicular. Soft systolic murmur at the cardiac apex." },
    palpation: { ru: "Живот мягкий, безболезненный.", kk: "Іш жұмсақ, ауырсынусыз.", en: "Abdomen soft, non-tender." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  community_pneumonia: {
    vitals: { hr: "96", bp: "122/78", spo2: "94", temp: "38.5", rr: "22" },
    abnormal: ["hr", "spo2", "temp", "rr"],
    inspection: { ru: "Состояние средней тяжести, кашель с гнойной мокротой.", kk: "Жағдайы орташа ауыр, іріңді қақырықпен жөтел.", en: "Moderate general condition, cough with purulent sputum." },
    auscultation: { ru: "Влажные хрипы в нижних отделах лёгких, дыхание ослаблено.", kk: "Өкпенің төменгі бөлігінде ылғалды сырылдар, тыныс әлсіреген.", en: "Moist crackles in the lower lung zones, breath sounds diminished." },
    palpation: { ru: "Живот мягкий, безболезненный.", kk: "Іш жұмсақ, ауырсынусыз.", en: "Abdomen soft, non-tender." },
    percussion: { ru: "Участок притупления над зоной воспаления.", kk: "Қабыну аймағында тұйықталу учаскесі.", en: "Area of dullness over the zone of consolidation." },
  },
  hypertension_crisis: {
    vitals: { hr: "92", bp: "190/110", spo2: "97", temp: "36.7", rr: "18" },
    abnormal: ["bp"],
    inspection: { ru: "Гиперемия лица, пациент возбуждён, тревожен.", kk: "Бет гиперемиясы, науқас қозған, мазасыз.", en: "Facial flushing, patient agitated and anxious." },
    auscultation: { ru: "Дыхание везикулярное. Акцент II тона над аортой, тоны громкие.", kk: "Тыныс везикулалық. Аортада II тон акценті, тондар қатты.", en: "Breath sounds vesicular. Accentuated second heart sound over the aorta, heart sounds loud." },
    palpation: { ru: "Живот мягкий. Пульс напряжённый.", kk: "Іш жұмсақ. Тамыр соғуы кернеулі.", en: "Abdomen soft. Pulse tense." },
    percussion: { ru: "Расширение левой границы сердца.", kk: "Жүректің сол жақ шекарасы кеңейген.", en: "Enlargement of the left cardiac border." },
  },
  diabetes_t2_debut: {
    vitals: { hr: "84", bp: "130/82", spo2: "98", temp: "36.6", rr: "17" },
    abnormal: [],
    inspection: { ru: "Сухость кожи и слизистых, расчёсы. Запаха ацетона нет.", kk: "Тері мен шырыштың құрғақтығы, тырнау іздері. Ацетон иісі жоқ.", en: "Dry skin and mucous membranes, excoriations. No acetone odor." },
    auscultation: { ru: "Дыхание везикулярное. Тоны сердца ясные.", kk: "Тыныс везикулалық. Жүрек тондары анық.", en: "Breath sounds vesicular. Heart sounds clear." },
    palpation: { ru: "Живот мягкий, безболезненный.", kk: "Іш жұмсақ, ауырсынусыз.", en: "Abdomen soft, non-tender." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  cystitis_female: {
    vitals: { hr: "80", bp: "118/75", spo2: "99", temp: "37.1", rr: "16" },
    abnormal: [],
    inspection: { ru: "Общее состояние удовлетворительное.", kk: "Жалпы жағдайы қанағаттанарлық.", en: "General condition satisfactory." },
    auscultation: { ru: "Дыхание и тоны сердца без патологии.", kk: "Тыныс пен жүрек тондары патологиясыз.", en: "Breath sounds and heart sounds within normal limits." },
    palpation: { ru: "Болезненность над лоном. Симптом поколачивания отрицательный с обеих сторон.", kk: "Шат үсті ауырсынады. Тоқылдату симптомы екі жағынан теріс.", en: "Tenderness over the pubic area. Costovertebral angle tenderness negative bilaterally." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  stable_angina: {
    vitals: { hr: "78", bp: "138/85", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "В покое жалоб нет, состояние удовлетворительное.", kk: "Тыныштықта шағым жоқ, жағдайы қанағаттанарлық.", en: "No complaints at rest, general condition satisfactory." },
    auscultation: { ru: "Дыхание везикулярное. Тоны сердца приглушены, ритм правильный.", kk: "Тыныс везикулалық. Жүрек тондары тұйық, ырғағы дұрыс.", en: "Breath sounds vesicular. Heart sounds muffled, regular rhythm." },
    palpation: { ru: "Живот мягкий. Отёков нет.", kk: "Іш жұмсақ. Ісіну жоқ.", en: "Abdomen soft. No edema." },
    percussion: { ru: "Левая граница сердца по среднеключичной линии.", kk: "Жүректің сол шекарасы орта бұғана сызығында.", en: "Left cardiac border at the midclavicular line." },
  },
  heart_failure: {
    vitals: { hr: "100", bp: "110/70", spo2: "93", temp: "36.6", rr: "24" },
    abnormal: ["hr", "spo2", "rr"],
    inspection: { ru: "Ортопноэ, акроцианоз, отёки голеней и стоп.", kk: "Ортопноэ, акроцианоз, балтыр мен табан ісінуі.", en: "Orthopnea, acrocyanosis, edema of the lower legs and feet." },
    auscultation: { ru: "Влажные хрипы в нижних отделах лёгких. Тоны сердца глухие, ритм галопа.", kk: "Өкпенің төменгі бөлігінде ылғалды сырылдар. Жүрек тондары тұйық, шоқырақ ырғағы.", en: "Moist crackles in the lower lung zones. Heart sounds distant, gallop rhythm." },
    palpation: { ru: "Печень увеличена, болезненна. Пастозность голеней.", kk: "Бауыр ұлғайған, ауырады. Балтыр пастозды.", en: "Liver enlarged and tender. Pitting edema of the lower legs." },
    percussion: { ru: "Расширение границ сердца, притупление в нижних отделах лёгких.", kk: "Жүрек шекаралары кеңейген, өкпе төменінде тұйықталу.", en: "Enlarged cardiac borders, dullness to percussion in the lower lung zones." },
  },
  copd_exacerbation: {
    vitals: { hr: "98", bp: "132/82", spo2: "89", temp: "37.4", rr: "26" },
    abnormal: ["hr", "spo2", "rr"],
    inspection: { ru: "Одышка в покое, участие вспомогательной мускулатуры, цианоз губ.", kk: "Тыныштықтағы ентігу, көмекші бұлшықет қатысуы, ерін цианозы.", en: "Dyspnea at rest, accessory muscle use, lip cyanosis." },
    auscultation: { ru: "Дыхание ослаблено, рассеянные сухие свистящие хрипы, удлинённый выдох.", kk: "Тыныс әлсіреген, шашыранды құрғақ ысқырық сырылдар, ұзартылған дем шығару.", en: "Breath sounds diminished, scattered dry wheezes, prolonged expiration." },
    palpation: { ru: "Грудная клетка эмфизематозная, ригидная.", kk: "Кеуде қуысы эмфиземалы, қатаң.", en: "Barrel-shaped, rigid chest." },
    percussion: { ru: "Коробочный перкуторный звук над лёгкими.", kk: "Өкпе үстінде жәшік тәрізді перкуссия дыбысы.", en: "Hyperresonant (box) percussion note over the lungs." },
  },
  hypothyroidism: {
    vitals: { hr: "58", bp: "110/72", spo2: "98", temp: "36.1", rr: "14" },
    abnormal: ["hr"],
    inspection: { ru: "Сухая кожа, отёчность лица, замедленность реакций.", kk: "Құрғақ тері, бет ісінуі, реакциялардың баяулауы.", en: "Dry skin, facial puffiness, slowed reactions." },
    auscultation: { ru: "Дыхание везикулярное. Тоны сердца приглушены, брадикардия.", kk: "Тыныс везикулалық. Жүрек тондары тұйық, брадикардия.", en: "Breath sounds vesicular. Heart sounds muffled, bradycardia." },
    palpation: { ru: "Живот мягкий. Щитовидная железа плотноватая, не увеличена.", kk: "Іш жұмсақ. Қалқанша без тығыздау, ұлғаймаған.", en: "Abdomen soft. Thyroid gland slightly firm, not enlarged." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  migraine: {
    vitals: { hr: "76", bp: "122/78", spo2: "99", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Вне приступа состояние удовлетворительное. Очаговой неврологической симптоматики и менингеальных знаков нет.", kk: "Ұстама болмаған кезде жағдайы қанағаттанарлық. Ошақты неврологиялық симптоматика мен менингеалды белгілер жоқ.", en: "Between episodes general condition satisfactory. No focal neurological deficits or meningeal signs." },
    auscultation: { ru: "Дыхание и тоны сердца без патологии.", kk: "Тыныс пен жүрек тондары патологиясыз.", en: "Breath sounds and heart sounds within normal limits." },
    palpation: { ru: "Живот мягкий, безболезненный.", kk: "Іш жұмсақ, ауырсынусыз.", en: "Abdomen soft, non-tender." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  peptic_ulcer: {
    vitals: { hr: "82", bp: "120/78", spo2: "98", temp: "36.7", rr: "16" },
    abnormal: [],
    inspection: { ru: "Состояние удовлетворительное, лёгкая бледность кожи.", kk: "Жағдайы қанағаттанарлық, тері сәл бозарған.", en: "General condition satisfactory, mild pallor of the skin." },
    auscultation: { ru: "Дыхание и тоны сердца без патологии.", kk: "Тыныс пен жүрек тондары патологиясыз.", en: "Breath sounds and heart sounds within normal limits." },
    palpation: { ru: "Болезненность в эпигастрии при глубокой пальпации, мышечного напряжения нет.", kk: "Терең пальпацияда эпигастрийде ауырсыну, бұлшықет кернеуі жоқ.", en: "Tenderness in the epigastrium on deep palpation, no muscular guarding." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  // ─── Cardiology (new) ──────────────────────────────────────
  atrial_fib: {
    vitals: { hr: "118", bp: "138/86", spo2: "96", temp: "36.6", rr: "18" },
    abnormal: ["hr"],
    inspection: { ru: "Состояние удовлетворительное, без выраженного дискомфорта.", kk: "Жағдайы қанағаттанарлық, ауыр ыңғайсыздық жоқ.", en: "General condition satisfactory, no significant discomfort." },
    auscultation: { ru: "Тоны сердца аритмичные с разной громкостью, ЧСС 118. Дыхание везикулярное.", kk: "Жүрек тондары ырғақсыз, әр түрлі қаттылықта, ЖСЖ 118. Тыныс везикулалық.", en: "Heart sounds arrhythmic with variable intensity, HR 118. Breath sounds vesicular." },
    palpation: { ru: "Пульс аритмичный, дефицит пульса. Печень не увеличена. Голени без отёков.", kk: "Тамыр соғуы ырғақсыз, тамыр соғу тапшылығы. Бауыр ұлғаймаған. Балтыр ісінуі жоқ.", en: "Pulse irregular, pulse deficit present. Liver not enlarged. No lower leg edema." },
    percussion: { ru: "Левая граница сердца по среднеключичной линии.", kk: "Жүректің сол шекарасы орта бұғана сызығында.", en: "Left cardiac border at the midclavicular line." },
  },
  acute_mi: {
    vitals: { hr: "98", bp: "108/68", spo2: "95", temp: "36.8", rr: "22" },
    abnormal: ["hr", "rr"],
    inspection: { ru: "Бледность, холодный липкий пот, выражение страдания на лице, беспокойство.", kk: "Бозарған, суық жабысқақ тер, бетте азап белгісі, мазасыздық.", en: "Pallor, cold clammy sweat, distressed facial expression, restlessness." },
    auscultation: { ru: "Тоны сердца глухие, ритм правильный. Дыхание везикулярное, без хрипов.", kk: "Жүрек тондары тұйық, ырғағы дұрыс. Тыныс везикулалық, сырылсыз.", en: "Heart sounds distant, regular rhythm. Breath sounds vesicular, no adventitious sounds." },
    palpation: { ru: "Болезненности в грудной клетке при пальпации нет (боль не воспроизводится).", kk: "Кеудеде пальпацияда ауырсыну жоқ (ауырсыну қайталанбайды).", en: "No chest wall tenderness on palpation (pain is not reproducible)." },
    percussion: { ru: "Лёгочный звук ясный. Границы сердца не расширены.", kk: "Өкпе дыбысы анық. Жүрек шекаралары кеңеймеген.", en: "Lung percussion note clear. Cardiac borders not enlarged." },
  },
  hypertension_essential: {
    vitals: { hr: "84", bp: "162/98", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: ["bp"],
    inspection: { ru: "Состояние удовлетворительное, лёгкая гиперемия лица. ИМТ 29.", kk: "Жағдайы қанағаттанарлық, бет сәл қызарған. ДСИ 29.", en: "General condition satisfactory, mild facial flushing. BMI 29." },
    auscultation: { ru: "Акцент II тона над аортой. Дыхание везикулярное.", kk: "Аортада II тон акценті. Тыныс везикулалық.", en: "Accentuated aortic component of S2. Vesicular breath sounds." },
    palpation: { ru: "Пульс напряжённый, ритмичный. Отёков нет.", kk: "Тамыр соғуы кернеулі, ырғақты. Ісіну жоқ.", en: "Pulse tense, regular rhythm. No edema." },
    percussion: { ru: "Расширение левой границы сердца на 0.5 см влево.", kk: "Жүректің сол шекарасы солға 0,5 см кеңейген.", en: "Left cardiac border displaced 0.5 cm to the left." },
  },
  unstable_angina: {
    vitals: { hr: "76", bp: "144/88", spo2: "97", temp: "36.6", rr: "16" },
    abnormal: ["bp"],
    inspection: { ru: "В покое жалоб нет, состояние удовлетворительное.", kk: "Тыныштықта шағым жоқ, жағдайы қанағаттанарлық.", en: "No complaints at rest, general condition satisfactory." },
    auscultation: { ru: "Тоны сердца приглушены, ритм правильный. Дыхание везикулярное.", kk: "Жүрек тондары тұйық, ырғағы дұрыс. Тыныс везикулалық.", en: "Heart sounds muffled, regular rhythm. Vesicular breath sounds." },
    palpation: { ru: "Пульс ритмичный. Отёков нет. Печень не увеличена.", kk: "Тамыр соғуы ырғақты. Ісіну жоқ. Бауыр ұлғаймаған.", en: "Pulse regular. No edema. Liver not enlarged." },
    percussion: { ru: "Левая граница сердца по среднеключичной линии.", kk: "Жүректің сол шекарасы орта бұғана сызығында.", en: "Left cardiac border at the midclavicular line." },
  },
  dvt: {
    vitals: { hr: "84", bp: "126/78", spo2: "97", temp: "37.2", rr: "16" },
    abnormal: ["temp"],
    inspection: { ru: "Правая голень увеличена в окружности на 4 см, отёчна, кожа цианотична с глянцевым оттенком. Симптом Хоманса положительный.", kk: "Оң балтыр айналасы 4 см ұлғайған, ісінген, тері жылтыр көкшіл реңкті. Хоманс симптомы оң.", en: "Right lower leg circumference increased by 4 cm, edematous, skin cyanotic with a glossy appearance. Homans' sign positive." },
    auscultation: { ru: "Лёгкие и сердце без патологии.", kk: "Өкпе мен жүрек патологиясыз.", en: "Lungs and heart unremarkable." },
    palpation: { ru: "Болезненность по ходу подколенной вены справа, плотные тяжи. Левая голень не изменена.", kk: "Оң жақта тізе асты венасы бойынша ауырсыну, тығыз баулар. Сол балтыр өзгермеген.", en: "Tenderness along the right popliteal vein, palpable cord. Left lower leg unchanged." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  // ─── Endocrinology (new) ───────────────────────────────────
  dka_t1: {
    vitals: { hr: "118", bp: "98/62", spo2: "98", temp: "36.4", rr: "28" },
    abnormal: ["hr", "rr"],
    inspection: { ru: "Запах ацетона изо рта, сухость кожи и слизистых, заострённые черты лица, дыхание Куссмауля (глубокое, шумное).", kk: "Аузынан ацетон иісі, тері мен шырыштың құрғақтығы, бет сүйір, Куссмауль тынысы (терең, шулы).", en: "Acetone breath odor, dry skin and mucous membranes, sunken facial features, Kussmaul breathing (deep, noisy)." },
    auscultation: { ru: "Дыхание учащённое, глубокое, без хрипов. Тоны сердца ясные, тахикардия.", kk: "Тыныс жиілеген, терең, сырылсыз. Жүрек тондары анық, тахикардия.", en: "Breathing rapid and deep, no wheezes. Heart sounds clear, tachycardia." },
    palpation: { ru: "Живот мягкий, болезненность в эпигастрии. Тургор кожи снижен. Признаки дегидратации.", kk: "Іш жұмсақ, эпигастрийде ауырсыну. Тері тургоры төмендеген. Дегидратация белгілері.", en: "Abdomen soft, epigastric tenderness. Skin turgor reduced. Signs of dehydration." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  graves: {
    vitals: { hr: "112", bp: "138/68", spo2: "98", temp: "37.4", rr: "18" },
    abnormal: ["hr", "temp"],
    inspection: { ru: "Тревожна, мелкий тремор кистей, влажная горячая кожа, экзофтальм слева. Похудание.", kk: "Мазасыз, қол ұсақ дірілі, ылғал ыстық тері, сол жақта экзофтальм. Арықтаған.", en: "Anxious, fine hand tremor, warm moist skin, left-sided exophthalmos. Weight loss." },
    auscultation: { ru: "Тахикардия, тоны сердца громкие. Дыхание везикулярное.", kk: "Тахикардия, жүрек тондары қатты. Тыныс везикулалық.", en: "Tachycardia, heart sounds loud. Vesicular breath sounds." },
    palpation: { ru: "Щитовидная железа диффузно увеличена II степени, плотноэластична, безболезненна. Положительный симптом Грефе.", kk: "Қалқанша без диффузды II дәрежеде ұлғайған, тығыз серпімді, ауырсынусыз. Грефе симптомы оң.", en: "Thyroid gland diffusely enlarged grade II, firm-elastic, non-tender. Graefe's sign positive." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  metabolic_syndrome: {
    vitals: { hr: "82", bp: "142/88", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: ["bp"],
    inspection: { ru: "Абдоминальное ожирение (ОТ 112 см), ИМТ 34. Состояние удовлетворительное.", kk: "Абдоминалды семіздік (БА 112 см), ДСИ 34. Жағдайы қанағаттанарлық.", en: "Abdominal obesity (waist circumference 112 cm), BMI 34. General condition satisfactory." },
    auscultation: { ru: "Тоны сердца приглушены, ритмичные. Дыхание везикулярное.", kk: "Жүрек тондары тұйық, ырғақты. Тыныс везикулалық.", en: "Heart sounds muffled, regular rhythm. Vesicular breath sounds." },
    palpation: { ru: "Живот мягкий, безболезненный. Печень по краю рёберной дуги, безболезненна.", kk: "Іш жұмсақ, ауырсынусыз. Бауыр қабырға доғасы бойымен, ауырсынусыз.", en: "Abdomen soft, non-tender. Liver palpable at the costal margin, non-tender." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  nodular_goiter: {
    vitals: { hr: "76", bp: "120/76", spo2: "99", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Общее состояние удовлетворительное. Визуально шея симметрична, узел не виден.", kk: "Жалпы жағдайы қанағаттанарлық. Көру арқылы мойын симметриялы, түйін көрінбейді.", en: "General condition satisfactory. Neck visually symmetric, no nodule visible." },
    auscultation: { ru: "Тоны сердца ясные, ритм правильный. Дыхание везикулярное.", kk: "Жүрек тондары анық, ырғағы дұрыс. Тыныс везикулалық.", en: "Heart sounds clear, regular rhythm. Vesicular breath sounds." },
    palpation: { ru: "В правой доле щитовидной железы пальпируется узел 2.5 см, эластичный, подвижный, безболезненный. Лимфоузлы не увеличены.", kk: "Қалқанша безінің оң бөлшегінде 2,5 см түйін пальпацияланады, серпімді, жылжымалы, ауырсынусыз. Лимфа түйіндері ұлғаймаған.", en: "A 2.5 cm elastic, mobile, non-tender nodule palpable in the right thyroid lobe. Lymph nodes not enlarged." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  cushing_iatrogenic: {
    vitals: { hr: "82", bp: "158/92", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: ["bp"],
    inspection: { ru: "Лунообразное лицо, гиперемия щёк, отложение жира в области шеи и живота, тонкие конечности. На животе багровые стрии шириной до 1 см.", kk: "Ай тәрізді бет, бет ұрттарының гиперемиясы, мойын мен ішке май шөгуі, аяқ-қол жіңішке. Іште 1 см ені бар қызыл стрилер.", en: "Moon face, facial plethora, fat deposition over the neck and abdomen, thin extremities. Purple striae up to 1 cm wide on the abdomen." },
    auscultation: { ru: "Тоны сердца приглушены, ритмичные.", kk: "Жүрек тондары тұйық, ырғақты.", en: "Heart sounds muffled, regular rhythm." },
    palpation: { ru: "Кожа тонкая, легко травмируется. Гематомы на голенях.", kk: "Тері жұқа, оңай жарақаттанады. Балтырларда гематомалар.", en: "Skin thin, easily bruised. Ecchymoses on the lower legs." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  addison: {
    vitals: { hr: "92", bp: "98/58", spo2: "98", temp: "36.4", rr: "18" },
    abnormal: ["bp"],
    inspection: { ru: "Гиперпигментация ладонных складок, локтей, дёсен и слизистой полости рта. Похудание. Ортостатическая гипотензия (АД лёжа 108/65, стоя 88/55).", kk: "Алақан қыртыстарының, шынтақтардың, қызыл иек пен ауыз шырышының гиперпигментациясы. Арықтаған. Ортостатикалық гипотензия.", en: "Hyperpigmentation of palmar creases, elbows, gums, and oral mucosa. Weight loss. Orthostatic hypotension (BP supine 108/65, standing 88/55 mmHg)." },
    auscultation: { ru: "Тоны сердца приглушены, ритмичные. Дыхание везикулярное.", kk: "Жүрек тондары тұйық, ырғақты. Тыныс везикулалық.", en: "Heart sounds muffled, regular rhythm. Vesicular breath sounds." },
    palpation: { ru: "Живот мягкий. Печень и селезёнка не увеличены.", kk: "Іш жұмсақ. Бауыр мен көкбауыр ұлғаймаған.", en: "Abdomen soft. Liver and spleen not enlarged." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  // ─── Gastroenterology (new) ────────────────────────────────
  acute_pancreatitis: {
    vitals: { hr: "108", bp: "118/72", spo2: "96", temp: "37.6", rr: "20" },
    abnormal: ["hr", "temp", "rr"],
    inspection: { ru: "Состояние средней тяжести, лицо страдальческое, кожные покровы бледные.", kk: "Жағдайы орташа ауыр, бетте азап белгісі, тері бозарған.", en: "Moderate general condition, distressed facial expression, pale skin." },
    auscultation: { ru: "Дыхание везикулярное, тахикардия. Перистальтика ослаблена.", kk: "Тыныс везикулалық, тахикардия. Перистальтика әлсіреген.", en: "Vesicular breath sounds, tachycardia. Bowel sounds diminished." },
    palpation: { ru: "Болезненность и резистентность в эпигастрии и левом подреберье. Симптомы Воскресенского, Мейо-Робсона положительные.", kk: "Эпигастрий мен сол қабырға астында ауырсыну мен резистенттілік. Воскресенский, Мейо-Робсон симптомдары оң.", en: "Tenderness and resistance in the epigastrium and left hypochondrium. Voskresensky's sign and Mayo-Robson's sign positive." },
    percussion: { ru: "Притупление в эпигастрии (отёк поджелудочной), тимпанит над раздутыми петлями.", kk: "Эпигастрийде тұйықталу (ұйқы безі ісінуі), кеңейген ілмектердің үстінде тимпанит.", en: "Dullness to percussion in the epigastrium (pancreatic edema), tympany over distended bowel loops." },
  },
  acute_cholecystitis: {
    vitals: { hr: "92", bp: "128/78", spo2: "98", temp: "38.0", rr: "18" },
    abnormal: ["hr", "temp"],
    inspection: { ru: "Состояние средней тяжести. Лёгкая иктеричность склер. ИМТ 31.", kk: "Жағдайы орташа ауыр. Көздің ағы сәл сарғайған. ДСИ 31.", en: "Moderate general condition. Mild scleral icterus. BMI 31." },
    auscultation: { ru: "Тоны сердца ясные, тахикардия. Дыхание везикулярное.", kk: "Жүрек тондары анық, тахикардия. Тыныс везикулалық.", en: "Heart sounds clear, tachycardia. Vesicular breath sounds." },
    palpation: { ru: "Резкая болезненность в правом подреберье. Симптом Мерфи положительный. Симптом Ортнера+. Желчный пузырь не пальпируется.", kk: "Оң қабырға астында өткір ауырсыну. Мерфи симптомы оң. Ортнер симптомы+. Өт қабы пальпацияланбайды.", en: "Severe tenderness in the right hypochondrium. Murphy's sign positive. Ortner's sign positive. Gallbladder not palpable." },
    percussion: { ru: "Симптом Ортнера положительный (болезненность при поколачивании по правой рёберной дуге).", kk: "Ортнер симптомы оң (оң қабырға доғасын тоқылдатқанда ауырсыну).", en: "Ortner's sign positive (tenderness on percussion over the right costal arch)." },
  },
  gerd: {
    vitals: { hr: "76", bp: "128/82", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Состояние удовлетворительное. ИМТ 28.", kk: "Жағдайы қанағаттанарлық. ДСИ 28.", en: "General condition satisfactory. BMI 28." },
    auscultation: { ru: "Дыхание везикулярное. Тоны сердца ясные.", kk: "Тыныс везикулалық. Жүрек тондары анық.", en: "Breath sounds vesicular. Heart sounds clear." },
    palpation: { ru: "Живот мягкий, болезненность в эпигастрии слабая. Печень по краю рёберной дуги.", kk: "Іш жұмсақ, эпигастрийде ауырсыну әлсіз. Бауыр қабырға доғасы бойымен.", en: "Abdomen soft, mild epigastric tenderness. Liver palpable at the costal margin." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  ibs_d: {
    vitals: { hr: "78", bp: "118/72", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Состояние удовлетворительное. Признаков дегидратации нет, масса тела сохранена.", kk: "Жағдайы қанағаттанарлық. Дегидратация белгілері жоқ, дене салмағы сақталған.", en: "General condition satisfactory. No signs of dehydration, body weight preserved." },
    auscultation: { ru: "Перистальтика кишечника усилена. Сердце и лёгкие без патологии.", kk: "Ішек перистальтикасы күшейген. Жүрек пен өкпе патологиясыз.", en: "Bowel sounds hyperactive. Heart and lungs unremarkable." },
    palpation: { ru: "Болезненность по ходу толстой кишки, особенно сигмовидной. Без мышечного напряжения, без объёмных образований.", kk: "Тоқ ішек бойымен, әсіресе сигма бойынша ауырсыну. Бұлшықет кернеуінсіз, түзілістерсіз.", en: "Tenderness along the colon, most pronounced over the sigmoid. No muscular guarding, no palpable masses." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  uc_flare: {
    vitals: { hr: "94", bp: "108/68", spo2: "98", temp: "37.4", rr: "18" },
    abnormal: ["hr", "temp"],
    inspection: { ru: "Состояние средней тяжести. Бледность кожных покровов. Признаки потери веса.", kk: "Жағдайы орташа ауыр. Тері бозарған. Салмақ жоғалту белгілері.", en: "Moderate general condition. Pale skin. Signs of weight loss." },
    auscultation: { ru: "Перистальтика усилена. Тоны сердца ясные, тахикардия.", kk: "Перистальтика күшейген. Жүрек тондары анық, тахикардия.", en: "Bowel sounds hyperactive. Heart sounds clear, tachycardia." },
    palpation: { ru: "Болезненность по ходу левой половины толстой кишки. Сигмовидная кишка спазмированная, болезненная.", kk: "Тоқ ішектің сол жартысы бойымен ауырсыну. Сигма ішек спазмға ұшыраған, ауырады.", en: "Tenderness along the left colon. Sigmoid colon spastic and tender." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  hep_a: {
    vitals: { hr: "70", bp: "118/74", spo2: "98", temp: "37.2", rr: "16" },
    abnormal: [],
    inspection: { ru: "Иктеричность склер и кожи. Моча тёмная, кал ахоличен. Геморрагической сыпи нет.", kk: "Көздің ағы мен тері сарғайған. Зәр қара, нәжіс ағарған. Геморрагиялық бөртпе жоқ.", en: "Scleral and cutaneous jaundice. Dark urine, acholic stools. No hemorrhagic rash." },
    auscultation: { ru: "Тоны сердца ясные, ритмичные. Дыхание везикулярное.", kk: "Жүрек тондары анық, ырғақты. Тыныс везикулалық.", en: "Heart sounds clear, regular rhythm. Vesicular breath sounds." },
    palpation: { ru: "Печень увеличена на 2 см ниже рёберной дуги, болезненна, эластична. Селезёнка не пальпируется.", kk: "Бауыр қабырға доғасынан 2 см төмен ұлғайған, ауырады, серпімді. Көкбауыр пальпацияланбайды.", en: "Liver enlarged 2 cm below the costal margin, tender, elastic. Spleen not palpable." },
    percussion: { ru: "Размеры печени по Курлову увеличены.", kk: "Курлов бойынша бауыр өлшемдері ұлғайған.", en: "Liver dimensions by Kurlov's method enlarged." },
  },
  // ─── Infectious (new) ──────────────────────────────────────
  salmonellosis: {
    vitals: { hr: "100", bp: "108/68", spo2: "98", temp: "38.5", rr: "18" },
    abnormal: ["hr", "temp"],
    inspection: { ru: "Состояние средней тяжести. Сухость слизистых, обложенный язык. Признаки умеренной дегидратации.", kk: "Жағдайы орташа ауыр. Шырыштардың құрғақтығы, тіл қаптамалы. Орташа дегидратация белгілері.", en: "Moderate general condition. Dry mucous membranes, coated tongue. Signs of moderate dehydration." },
    auscultation: { ru: "Перистальтика кишечника усилена. Тоны сердца ясные.", kk: "Ішек перистальтикасы күшейген. Жүрек тондары анық.", en: "Bowel sounds hyperactive. Heart sounds clear." },
    palpation: { ru: "Разлитая болезненность по всему животу, больше в околопупочной области. Симптомов раздражения брюшины нет.", kk: "Бүкіл іш бойынша шашыранды ауырсыну, кіндік маңында көбірек. Іш құрсақ тітіркену симптомдары жоқ.", en: "Diffuse abdominal tenderness, most pronounced in the periumbilical region. No signs of peritoneal irritation." },
    percussion: { ru: "Тимпанит над петлями кишечника.", kk: "Ішек ілмектерінің үстінде тимпанит.", en: "Tympany over distended bowel loops." },
  },
  typhoid: {
    vitals: { hr: "78", bp: "108/68", spo2: "98", temp: "39.4", rr: "18" },
    abnormal: ["temp"],
    inspection: { ru: "Заторможен, тифозный статус. Розеолезная сыпь на животе (4–6 элементов). Язык обложен бело-сером налётом, по краям красный («тифозный язык»).", kk: "Селсоқ, тиф статусы. Іште розеолалы бөртпе (4–6 элемент). Тіл ақ-сұр қаптамамен, шеттері қызыл («тифоз тілі»).", en: "Lethargic, typhoid status. Rose-spot rash on the abdomen (4–6 elements). Tongue coated with white-gray fur, red at the edges ('typhoid tongue')." },
    auscultation: { ru: "Тоны сердца глухие. Относительная брадикардия. Дыхание везикулярное.", kk: "Жүрек тондары тұйық. Салыстырмалы брадикардия. Тыныс везикулалық.", en: "Heart sounds distant. Relative bradycardia. Vesicular breath sounds." },
    palpation: { ru: "Гепатоспленомегалия (печень +3 см, селезёнка пальпируется). Болезненность в правой подвздошной области.", kk: "Гепатоспленомегалия (бауыр +3 см, көкбауыр пальпацияланады). Оң мықын аумағында ауырсыну.", en: "Hepatosplenomegaly (liver +3 cm, spleen palpable). Tenderness in the right iliac fossa." },
    percussion: { ru: "Симптом Падалки положительный (укорочение перкуторного звука в правой подвздошной области).", kk: "Падалка симптомы оң (оң мықын аумағында перкуссия дыбысының қысқаруы).", en: "Padalka's sign positive (dullness to percussion in the right iliac fossa)." },
  },
  rotavirus: {
    vitals: { hr: "88", bp: "118/72", spo2: "98", temp: "37.6", rr: "16" },
    abnormal: ["temp"],
    inspection: { ru: "Состояние удовлетворительное. Лёгкая бледность, сухость губ.", kk: "Жағдайы қанағаттанарлық. Жеңіл бозару, ерін құрғақтығы.", en: "General condition satisfactory. Mild pallor, dry lips." },
    auscultation: { ru: "Перистальтика усилена. Сердце и лёгкие без патологии.", kk: "Перистальтика күшейген. Жүрек пен өкпе патологиясыз.", en: "Bowel sounds hyperactive. Heart and lungs unremarkable." },
    palpation: { ru: "Лёгкая разлитая болезненность живота, без напряжения мышц. Лимфоузлы не увеличены.", kk: "Іште жеңіл шашыранды ауырсыну, бұлшықет кернеуінсіз. Лимфа түйіндері ұлғаймаған.", en: "Mild diffuse abdominal tenderness, no muscular guarding. Lymph nodes not enlarged." },
    percussion: { ru: "Тимпанит над петлями кишечника.", kk: "Ішек ілмектерінің үстінде тимпанит.", en: "Tympany over distended bowel loops." },
  },
  erysipelas: {
    vitals: { hr: "98", bp: "138/82", spo2: "97", temp: "38.6", rr: "18" },
    abnormal: ["hr", "temp"],
    inspection: { ru: "На правой голени — ярко-эритематозный, отёчный, чётко отграниченный участок размером 20×15 см. Кожа горячая, напряжённая. Регионарный лимфангит.", kk: "Оң балтырда — ашық эритемалы, ісінген, айқын шектелген 20×15 см аумақ. Тері ыстық, кернеулі. Аймақтық лимфангит.", en: "Bright erythematous, edematous, sharply demarcated lesion measuring 20×15 cm on the right lower leg. Skin warm and tense. Regional lymphangitis." },
    auscultation: { ru: "Тоны сердца ясные, тахикардия. Дыхание везикулярное.", kk: "Жүрек тондары анық, тахикардия. Тыныс везикулалық.", en: "Heart sounds clear, tachycardia. Vesicular breath sounds." },
    palpation: { ru: "Очаг резко болезненный, горячий, плотный. Паховые лимфоузлы справа увеличены, болезненны.", kk: "Ошақ өткір ауырады, ыстық, тығыз. Оң жақ шап лимфа түйіндері ұлғайған, ауырады.", en: "Focus is sharply tender, warm, and indurated. Right inguinal lymph nodes are enlarged and tender." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  chickenpox_adult: {
    vitals: { hr: "92", bp: "118/72", spo2: "97", temp: "38.7", rr: "18" },
    abnormal: ["hr", "temp"],
    inspection: { ru: "Полиморфная сыпь на туловище, лице, конечностях и волосистой части головы: пятна, папулы, везикулы с прозрачным содержимым, корочки одновременно («звёздное небо»).", kk: "Денеде, бетте, аяқ-қолда, шаш астында полиморфты бөртпе: дақтар, папулалар, мөлдір көпіршіктер, қабыршақтар бір мезетте («жұлдызды аспан»).", en: "Polymorphic rash on the trunk, face, extremities, and scalp: macules, papules, clear-fluid vesicles, and crusts present simultaneously ('starry sky' appearance)." },
    auscultation: { ru: "Дыхание везикулярное, без хрипов. Тоны сердца ясные.", kk: "Тыныс везикулалық, сырылсыз. Жүрек тондары анық.", en: "Breath sounds vesicular, no adventitious sounds. Heart sounds clear." },
    palpation: { ru: "Подчелюстные и шейные лимфоузлы слегка увеличены.", kk: "Жақ асты және мойын лимфа түйіндері сәл ұлғайған.", en: "Submandibular and cervical lymph nodes slightly enlarged." },
    percussion: { ru: "Лёгочный звук ясный.", kk: "Өкпе дыбысы анық.", en: "Lung percussion note clear." },
  },
  mononucleosis: {
    vitals: { hr: "92", bp: "118/72", spo2: "98", temp: "38.6", rr: "16" },
    abnormal: ["hr", "temp"],
    inspection: { ru: "Бледность лица с одутловатостью. Зев гиперемирован, миндалины увеличены II степени с белыми наложениями. Пятнистая сыпь на туловище (после амоксициллина).", kk: "Беті бозарған, ісіңкі. Жұтқыншақ гиперемиялы, бадамшалар II дәрежеде ұлғайған, ақ шөгінділермен. Денеде амоксициллиннен кейін дақты бөртпе.", en: "Facial pallor with puffiness. Oropharynx hyperemic; tonsils grade II enlarged with white exudate. Maculopapular rash on trunk (following amoxicillin)." },
    auscultation: { ru: "Тоны сердца ясные, тахикардия. Дыхание везикулярное.", kk: "Жүрек тондары анық, тахикардия. Тыныс везикулалық.", en: "Heart sounds clear, tachycardia. Vesicular breath sounds." },
    palpation: { ru: "Шейные лимфоузлы 2–3 см, плотноэластичные, болезненные. Печень +1 см, селезёнка пальпируется на 1.5 см ниже рёберной дуги.", kk: "Мойын лимфа түйіндері 2–3 см, тығыз серпімді, ауырады. Бауыр +1 см, көкбауыр қабырға доғасынан 1,5 см төмен.", en: "Cervical lymph nodes 2–3 cm, firm-elastic, tender. Liver +1 cm below costal margin; spleen palpable 1.5 cm below costal margin." },
    percussion: { ru: "Размеры печени и селезёнки увеличены.", kk: "Бауыр мен көкбауыр өлшемдері ұлғайған.", en: "Liver and spleen enlarged." },
  },
  // ─── Neurology (new) ───────────────────────────────────────
  ischemic_stroke: {
    vitals: { hr: "92", bp: "168/96", spo2: "97", temp: "36.7", rr: "16" },
    abnormal: ["hr", "bp"],
    inspection: { ru: "Сознание ясное, но моторная афазия. Опущен правый угол рта. Правая рука и нога — отсутствие активных движений (плегия). Дизартрия.", kk: "Есі анық, бірақ моторлы афазия. Оң жақ ауыз бұрышы түскен. Оң қол мен аяқта — белсенді қозғалыс жоқ (плегия). Дизартрия.", en: "Consciousness clear, but motor aphasia present. Right corner of mouth drooping. Right arm and leg: no active movement (plegia). Dysarthria." },
    auscultation: { ru: "Тоны сердца аритмичные (фибрилляция предсердий). Шум на сонной артерии слева.", kk: "Жүрек тондары ырғақсыз (жүрекше фибрилляциясы). Сол ұйқы артериясында шу.", en: "Heart sounds irregular (atrial fibrillation). Bruit over left carotid artery." },
    palpation: { ru: "Пульс аритмичный. Мышечный тонус справа снижен, рефлексы повышены. Симптом Бабинского справа+.", kk: "Тамыр соғу ырғақсыз. Оң жақта бұлшықет тонусы төмендеген, рефлекстер жоғары. Оң жақта Бабинский симптомы+.", en: "Pulse irregular. Muscle tone decreased on the right; reflexes hyperreflexic. Babinski sign positive on the right." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  epilepsy_gtcs: {
    vitals: { hr: "84", bp: "128/82", spo2: "98", temp: "36.7", rr: "16" },
    abnormal: [],
    inspection: { ru: "В сознании, заторможен (постиктальная сонливость). Прикус на боковой поверхности языка справа. На джинсах след мочи.", kk: "Есінде, селсоқ (ұстамадан кейінгі ұйқы). Оң жақта тілдің бүйірінде тістеу. Шалбарда зәр ізі.", en: "Conscious, lethargic (postictal somnolence). Bite mark on lateral surface of tongue on the right. Urinary incontinence evident on clothing." },
    auscultation: { ru: "Дыхание везикулярное. Тоны сердца ясные, ритмичные.", kk: "Тыныс везикулалық. Жүрек тондары анық, ырғақты.", en: "Breath sounds vesicular. Heart sounds clear and regular." },
    palpation: { ru: "Мышечный тонус снижен (постиктальный период), сухожильные рефлексы симметричные.", kk: "Бұлшықет тонусы төмендеген (ұстамадан кейінгі кезең), сіңір рефлекстері симметриялы.", en: "Muscle tone decreased (postictal period); deep tendon reflexes symmetric." },
    percussion: { ru: "Без особенностей. Менингеальных знаков нет.", kk: "Ерекшеліксіз. Менингеалды белгілер жоқ.", en: "Unremarkable. No meningeal signs." },
  },
  tension_headache: {
    vitals: { hr: "74", bp: "122/78", spo2: "99", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Утомлённый вид, нет очаговой симптоматики. Конъюнктива розовая, без инъекции.", kk: "Шаршаған, ошақты симптоматика жоқ. Конъюнктива қызғылт, инъекциясыз.", en: "Fatigued appearance; no focal neurological deficits. Conjunctivae pink, non-injected." },
    auscultation: { ru: "Тоны сердца ясные. Дыхание везикулярное.", kk: "Жүрек тондары анық. Тыныс везикулалық.", en: "Heart sounds clear. Breath sounds vesicular." },
    palpation: { ru: "Болезненность и напряжение перикраниальных мышц (трапециевидных, височных), особенно у затылка.", kk: "Перикраниалды бұлшықеттердің (трапеция тәрізді, шеке) ауырсынуы мен кернеуі, әсіресе шүйделе.", en: "Tenderness and tension of pericranial muscles (trapezius, temporalis), particularly in the occipital region." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  cervical_radiculopathy: {
    vitals: { hr: "78", bp: "126/80", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Вынужденная поза — голова наклонена влево. Лёгкая гипотрофия дельтовидной мышцы справа.", kk: "Мәжбүрлі қалып — бас солға қисайған. Оң жақта дельта тәрізді бұлшықеттің жеңіл гипотрофиясы.", en: "Antalgic posture — head tilted to the left. Mild hypotrophy of the right deltoid muscle." },
    auscultation: { ru: "Лёгкие и сердце без патологии.", kk: "Өкпе мен жүрек патологиясыз.", en: "Lungs and heart unremarkable." },
    palpation: { ru: "Болезненность остистых отростков C6–C7, паравертебральных точек справа. Сила в трицепсе 4/5 справа. Гипестезия III пальца правой кисти.", kk: "C6–C7 қылқан өсінділері, оң жақта паравертебралды нүктелер ауырады. Оң трицепс күші 4/5. Оң қолдың III саусағында гипестезия.", en: "Tenderness over C6–C7 spinous processes and right paravertebral points. Triceps strength 4/5 on the right. Hypesthesia of the right third finger." },
    percussion: { ru: "Симптом Спурлинга положительный справа (усиление боли при наклоне головы вправо с компрессией).", kk: "Оң жақта Спурлинг симптомы оң (басын оңға еңкейтіп қысқанда ауырсыну күшейеді).", en: "Spurling's test positive on the right (pain exacerbated by right lateral head tilt with axial compression)." },
  },
  diabetic_neuropathy: {
    vitals: { hr: "78", bp: "138/84", spo2: "98", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Кожа стоп сухая, гиперкератоз. Деформация ногтей. Ран и язв нет. Пульсация на тыле стопы и задней большеберцовой артерии сохранена.", kk: "Табан терісі құрғақ, гиперкератоз. Тырнақ деформациясы. Жара жоқ. Табанның арт жағында және артқы балтыр артериясында тамыр соғуы сақталған.", en: "Foot skin dry with hyperkeratosis. Nail deformity present. No wounds or ulcers. Dorsalis pedis and posterior tibial pulses intact bilaterally." },
    auscultation: { ru: "Дыхание везикулярное. Тоны сердца ясные.", kk: "Тыныс везикулалық. Жүрек тондары анық.", en: "Breath sounds vesicular. Heart sounds clear." },
    palpation: { ru: "Снижение тактильной чувствительности по типу «носков» билатерально. Монофиламент-тест: 5/10 точек.", kk: "Екі жақты «шұлық» түрінде тактильді сезімталдық төмен. Монофиламент-тест: 5/10 нүкте.", en: "Reduced tactile sensation in a 'stocking' distribution bilaterally. Monofilament test: 5/10 points." },
    percussion: { ru: "Снижение ахилловых рефлексов, коленные сохранены.", kk: "Ахилл рефлекстері төмендеген, тізе рефлекстері сақталған.", en: "Achilles reflexes diminished; knee reflexes preserved." },
  },
  bell_palsy: {
    vitals: { hr: "76", bp: "124/78", spo2: "99", temp: "36.6", rr: "16" },
    abnormal: [],
    inspection: { ru: "Асимметрия лица: справа сглажена носогубная складка, опущен угол рта, не закрывается глаз (лагофтальм), не наморщивает лоб. Слёзотечение справа.", kk: "Бет асимметриясы: оң жақта мұрын-ерін қыртысы тегіс, ауыз бұрышы түскен, көзін жұма алмайды (лагофтальм), маңдайды жинай алмайды. Оң көзден жас ағады.", en: "Facial asymmetry: right nasolabial fold flattened, right corner of mouth drooping, incomplete eye closure (lagophthalmos), inability to wrinkle forehead on the right. Epiphora on the right." },
    auscultation: { ru: "Лёгкие и сердце без патологии.", kk: "Өкпе мен жүрек патологиясыз.", en: "Lungs and heart unremarkable." },
    palpation: { ru: "Объём активных движений мимических мышц справа резко снижен. Чувствительность лица сохранена.", kk: "Оң жақта мимикалық бұлшықеттердің белсенді қозғалыс көлемі күрт төмендеген. Бет сезімталдығы сақталған.", en: "Range of active facial muscle movement markedly reduced on the right. Facial sensation intact." },
    percussion: { ru: "Симптом Хитровского справа+ (учащение мигания при перкуссии надбровья).", kk: "Оң жақта Хитровский симптомы+.", en: "Khitrovsky's sign positive on the right (increased blink rate on percussion of the supraorbital ridge)." },
  },
  // ─── Pulmonology (new) ─────────────────────────────────────
  asthma_exacerbation: {
    vitals: { hr: "108", bp: "128/82", spo2: "92", temp: "37.0", rr: "26" },
    abnormal: ["hr", "spo2", "rr"],
    inspection: { ru: "Пациентка возбуждена, говорит фразами (не предложениями). Положение ортопноэ. Участие вспомогательной мускулатуры в акте дыхания.", kk: "Науқас мазасыз, фразалармен сөйлейді. Ортопноэ. Демалу актісінде көмекші бұлшықет қатысады.", en: "Patient agitated, speaking in phrases (not full sentences). Orthopneic position. Accessory muscle use during breathing." },
    auscultation: { ru: "Удлинённый выдох. Рассеянные сухие свистящие хрипы на выдохе, билатерально.", kk: "Ұзартылған дем шығару. Дем шығаруда екі жақты шашыранды құрғақ ысқырық сырылдар.", en: "Prolonged expiration. Diffuse dry wheezes on expiration, bilateral." },
    palpation: { ru: "Грудная клетка эмфизематозна, экскурсия снижена.", kk: "Кеуде қуысы эмфиземалы, экскурсия төмендеген.", en: "Barrel-shaped chest; respiratory excursion reduced." },
    percussion: { ru: "Коробочный перкуторный звук над лёгкими.", kk: "Өкпе үстінде жәшік тәрізді перкуссия дыбысы.", en: "Hyperresonant (box) percussion note over the lungs." },
  },
  tb_lung: {
    vitals: { hr: "88", bp: "118/72", spo2: "96", temp: "37.6", rr: "18" },
    abnormal: ["temp"],
    inspection: { ru: "Похудание, бледность, влажная кожа. Состояние удовлетворительное.", kk: "Арықтаған, бозғылт, ылғал тері. Жағдайы қанағаттанарлық.", en: "Weight loss, pallor, moist skin. General condition satisfactory." },
    auscultation: { ru: "В верхних отделах правого лёгкого — ослабленное дыхание, единичные мелкопузырчатые влажные хрипы.", kk: "Оң өкпенің жоғарғы бөлігінде — әлсіреген тыныс, бірлі-жарым ұсақ көпіршікті ылғал сырылдар.", en: "Breath sounds diminished in the upper right lung zone; occasional fine crackles." },
    palpation: { ru: "Усиление голосового дрожания над зоной инфильтрата. Лимфоузлы шейные, надключичные пальпируются 0.5–1 см.", kk: "Инфильтрат үстінде дауыс дірілінің күшеюі. Мойын, бұғана үсті лимфа түйіндері 0,5–1 см.", en: "Increased vocal fremitus over the infiltrate zone. Cervical and supraclavicular lymph nodes palpable, 0.5–1 cm." },
    percussion: { ru: "Притупление перкуторного звука в верхних отделах справа.", kk: "Оң жақ жоғарғы бөлікте перкуссия дыбысы тұйықталған.", en: "Dullness to percussion in the upper right lung zone." },
  },
  acute_bronchitis: {
    vitals: { hr: "82", bp: "118/72", spo2: "98", temp: "37.4", rr: "16" },
    abnormal: ["temp"],
    inspection: { ru: "Состояние удовлетворительное. Лёгкая гиперемия зева, заложенность носа.", kk: "Жағдайы қанағаттанарлық. Жұтқыншақ сәл қызарған, мұрын бітелуі.", en: "General condition satisfactory. Mild oropharyngeal hyperemia, nasal congestion." },
    auscultation: { ru: "Дыхание жёсткое, единичные сухие хрипы, исчезающие после кашля. Тоны сердца ясные.", kk: "Тыныс қатты, бірлі-жарым құрғақ сырылдар, жөтелден кейін жоғалады. Жүрек тондары анық.", en: "Breath sounds harsh; occasional dry rhonchi disappearing after cough. Heart sounds clear." },
    palpation: { ru: "Лимфоузлы подчелюстные слегка увеличены, безболезненны.", kk: "Жақ асты лимфа түйіндері сәл ұлғайған, ауырсынусыз.", en: "Submandibular lymph nodes slightly enlarged, non-tender." },
    percussion: { ru: "Лёгочный звук ясный над всей поверхностью.", kk: "Өкпе дыбысы барлық жерде анық.", en: "Clear percussion note over all lung fields." },
  },
  pulmonary_embolism: {
    vitals: { hr: "116", bp: "108/68", spo2: "89", temp: "36.8", rr: "26" },
    abnormal: ["hr", "spo2", "rr"],
    inspection: { ru: "Состояние средней тяжести. Бледность, акроцианоз. Тревожна.", kk: "Жағдайы орташа ауыр. Бозару, акроцианоз. Мазасыз.", en: "General condition moderate severity. Pallor, acrocyanosis. Patient anxious." },
    auscultation: { ru: "Тахикардия, акцент II тона над лёгочной артерией. Дыхание ослаблено справа.", kk: "Тахикардия, өкпе артериясында II тон акценті. Оң жақта тыныс әлсіреген.", en: "Tachycardia; accentuated P2 over the pulmonary artery. Breath sounds diminished on the right." },
    palpation: { ru: "Шум трения плевры справа. Правая голень увеличена в окружности на 3 см (источник тромбоэмболии).", kk: "Оң жақта плевра үйкеліс шуы. Оң балтыр айналасы 3 см ұлғайған (тромбоэмболия көзі).", en: "Pleural friction rub on the right. Right calf circumference increased by 3 cm (source of thromboembolism)." },
    percussion: { ru: "Без особенностей.", kk: "Ерекшеліксіз.", en: "Unremarkable." },
  },
  pleural_effusion: {
    vitals: { hr: "92", bp: "128/82", spo2: "94", temp: "36.6", rr: "22" },
    abnormal: ["hr", "spo2", "rr"],
    inspection: { ru: "Состояние средней тяжести. Цианоз губ, отёчность голеней до колен. Положение полусидя.", kk: "Жағдайы орташа ауыр. Ерін цианозы, балтырлардың тізеге дейін ісінуі. Жартылай отырған қалып.", en: "General condition moderate severity. Lip cyanosis; bilateral lower-leg edema to the knees. Semi-recumbent position." },
    auscultation: { ru: "Справа в нижних отделах — резко ослаблено дыхание, бронхофония отсутствует. Слева — единичные влажные хрипы. Ритм галопа.", kk: "Оң жақ төменгі бөлікте — тыныс күрт әлсіреген, бронхофония жоқ. Сол жақта — бірлі-жарым ылғал сырылдар. Шоқырақ ырғағы.", en: "Right lower zone: markedly diminished breath sounds, bronchophony absent. Left side: occasional moist crackles. Gallop rhythm." },
    palpation: { ru: "Голосовое дрожание ослаблено справа. Печень увеличена. Отёки нижних конечностей.", kk: "Оң жақта дауыс дірілі әлсіреген. Бауыр ұлғайған. Аяқтар ісінген.", en: "Vocal fremitus diminished on the right. Liver enlarged. Lower-extremity edema." },
    percussion: { ru: "Тупой звук в нижних отделах правого лёгкого до уровня угла лопатки.", kk: "Оң өкпенің төменгі бөлігінде жауырын бұрышы деңгейіне дейін тұйық дыбыс.", en: "Dull percussion note in the right lower lung zone up to the level of the scapular angle." },
  },
  pneumothorax: {
    vitals: { hr: "102", bp: "118/74", spo2: "93", temp: "36.6", rr: "24" },
    abnormal: ["hr", "spo2", "rr"],
    inspection: { ru: "Высокий рост (190 см), низкий ИМТ (19). Состояние беспокойное, тахипноэ. Правая половина грудной клетки отстаёт в акте дыхания.", kk: "Биік бой (190 см), төмен ДСИ (19). Мазасыз, тахипноэ. Оң кеуде жартысы демалу актісінде кешігеді.", en: "Tall stature (190 cm), low BMI (19). Patient restless, tachypneic. Right hemithorax lagging on inspiration." },
    auscultation: { ru: "Справа дыхание не выслушивается. Слева — везикулярное. Тоны сердца смещены влево.", kk: "Оң жақта тыныс естілмейді. Сол жақта — везикулалық. Жүрек тондары солға ығысқан.", en: "No breath sounds on the right. Left side: vesicular breath sounds. Heart sounds shifted to the left." },
    palpation: { ru: "Голосовое дрожание справа отсутствует. Подкожной эмфиземы нет.", kk: "Оң жақта дауыс дірілі жоқ. Тері асты эмфиземасы жоқ.", en: "Vocal fremitus absent on the right. No subcutaneous emphysema." },
    percussion: { ru: "Тимпанит (коробочный звук) над правым гемитораксом.", kk: "Оң гемитораксте тимпанит (жәшік дыбысы).", en: "Tympanic (hyperresonant) percussion note over the right hemithorax." },
  },
};

/* Extra distractor tests — excessive for a routine polyclinic visit */
export const EXTRA_TESTS: Bi[] = [
  { ru: "Онкомаркеры (расширенная панель)", kk: "Онкомаркерлер (кеңейтілген панель)", en: "Tumor markers (extended panel)" },
  { ru: "МРТ всего тела", kk: "Бүкіл дененің МРТ-сы", en: "Whole-body MRI" },
  { ru: "Генетическое тестирование", kk: "Генетикалық тестілеу", en: "Genetic testing" },
  { ru: "ПЭТ-КТ всего тела", kk: "Бүкіл дененің ПЭТ-КТ-сы", en: "Whole-body PET-CT" },
];
